<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<!-- Métadonnées NuGet -->
		<PackageId>ContextCompiler.Modules.Readers.Excel</PackageId>

		<Description>
			Module de lecture de fichiers Excel pour ContextCompiler. Permet d'extraire des données structurées à partir de feuilles de calcul, facilitant ainsi l'intégration de données tabulaires dans les processus de compilation de contexte.
		</Description>

		<!-- Active la génération du package -->
		<IsPackable>true</IsPackable>
		<Configurations>Debug;Release;DebugLocal</Configurations>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'DebugLocal'">
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ClosedXML" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\Core\ContextCompiler.Abstractions\ContextCompiler.Abstractions.csproj" />
		<ProjectReference Include="..\ContextCompiler.Modules.Abstractions\ContextCompiler.Modules.Abstractions.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <None Update="schemas\ctxc.config.schema.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

	<ItemGroup>
		<Content Include="schemas\ctxc.config.schema.json">
			<PackagePath>contentFiles/any/schemas/ctxc.config.schema.json</PackagePath>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
</Project>
