<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Configurations>Debug;Release;DebugLocal</Configurations>
		<IsPackable>true</IsPackable>
		<PackageId>ContextCompiler.Modules.Abstractions</PackageId>
		<Description>
			Package d'abstractions des modules de ContextCompiler.
		</Description>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'DebugLocal'">
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\ContextCompiler.Abstractions\ContextCompiler.Abstractions.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="LICENSE.txt" Pack="true" PackagePath="" />
		<None Include="README.md" Pack="true" PackagePath="" />
	</ItemGroup>
</Project>
