<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Configurations>Debug;Release;DebugLocal</Configurations>
		<IsPackable>true</IsPackable>
		<PackageId>ContextCompiler.Modules.Engineering.DotNet</PackageId>
		<Description>
			Module d'ingénierie compiler une solution DotNet via ContextCompiler.
		</Description>
		<Authors>ContextCompiler</Authors>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'DebugLocal'">
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="PdfPig" />
		<PackageReference Include="Tabula" />
		<PackageReference Include="Tabula.Json" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ContextCompiler.Abstractions\ContextCompiler.Abstractions.csproj" />
		<ProjectReference Include="..\ContextCompiler.Modules.Abstractions\ContextCompiler.Modules.Abstractions.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="schemas\ctxc.config.schema.json">
			<PackagePath>contentFiles/any/schemas/ctxc.config.schema.json</PackagePath>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
</Project>
