<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Configurations>Debug;Release;DebugLocal</Configurations>
		<PackageId>ContextCompiler.Rag.Modules.LocalInMemory</PackageId>
		<Description>ContextCompiler module that adds local RAG capabilities.</Description>
		<IsPackable>true</IsPackable>
		<Title>Local RAG module</Title>
		<PackageTags>context;compiler;module;rag;embeddings;search</PackageTags>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)' == 'DebugLocal'">
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\..\..\Core\ContextCompiler.Modules.Abstractions\ContextCompiler.Modules.Abstractions.csproj" />
	</ItemGroup>
	<ItemGroup>
		<!--<PackageReference Include="FastBertTokenizer" />-->
		<PackageReference Include="Microsoft.Bcl.Memory" />
		<PackageReference Include="Microsoft.ML.Tokenizers" />
		<PackageReference Include="Microsoft.ML.Tokenizers.Data.Cl100kBase" />
		<PackageReference Include="SmartComponents.LocalEmbeddings" />
	</ItemGroup>
	<ItemGroup>
		<Content Include="onnx\all-MiniLM-L6-v2.onnx">
			<PackagePath>content/all-MiniLM-L6-v2.onnx</PackagePath>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="onnx\all-MiniLM-L6-v2_vocab.txt">
			<PackagePath>content/all-MiniLM-L6-v2_vocab.txt</PackagePath>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="" />
	</ItemGroup>
</Project>