using System.Text.Json;
using System.Text.Json.Nodes;

using ContextCompiler.Abstractions.Configuration;

namespace ContextCompiler.Configuration.Json;

internal sealed class SchemaAggregator : IConfigurationSchemaAggregator
{

    public bool CanAggregate(ISchema schema)
    {
        return Path.GetExtension(schema.Path) == ".json";
    }

    public static JsonObject LoadJsonObject(ISchema schema)
    {
        JsonNode? node = JsonNode.Parse(schema.Content);
        return node as JsonObject ?? [];
    }

    public Task<IAggregatedSchema> Aggregate(ISchema schema1, ISchema schema2)
    {
        JsonObject root = LoadJsonObject(schema1);

        JsonObject defs = root["$defs"] as JsonObject ?? [];
        root["$defs"] = defs;

        List<string> defNames = [];
        JsonObject module = LoadJsonObject(schema2);
        string defName = MakeSafeDefName(schema2, module);

        JsonObject rewritten = RewriteModuleSchemaForEmbedding(module, defName);
        defs[defName] = rewritten;
        defNames.Add(defName);

        MergeModuleOptionsDefIfPresent(root, rewritten, defName);

        if (defNames.Count > 0)
        {
            ApplyFilesOptionsOneOf(root, defNames);
        }

        root["$comment"] = "Generated by ctxc modules restore. Aggregates core schema + module schemas.";

        return Task.FromResult<IAggregatedSchema>(new JsonAggregatedSchema()
        {
            Content = root.ToJsonString(new JsonSerializerOptions { WriteIndented = true }),
            Name = $"{Path.GetFileNameWithoutExtension(schema1.Name)}_Aggregated",
            Path = schema1.Path
        });
    }

    private static void MergeModuleOptionsDefIfPresent(JsonObject root, JsonObject moduleSchema, string moduleDefName)
    {
        JsonObject? rootDefs = root["$defs"] as JsonObject;
        if (rootDefs?["moduleOptions"] is not JsonObject moduleOptionsDef)
        {
            return;
        }

        if (moduleSchema["$defs"] is not JsonObject moduleDefs)
        {
            return;
        }

        if (moduleDefs["moduleOptions"] is not JsonObject moduleProvidedOptions)
        {
            return;
        }

        if (moduleOptionsDef["properties"] is not JsonObject)
        {
            moduleOptionsDef["properties"] = new JsonObject();
        }

        if (moduleOptionsDef["oneOf"] is not JsonArray moduleOptionsOneOf)
        {
            moduleOptionsOneOf = [];
            moduleOptionsDef["oneOf"] = moduleOptionsOneOf;
        }

        //string moduleKey = DerivePluginKey(moduleSchema);

        JsonNode moduleExtractItemSchema = ExtractModuleExtractItemSchema(moduleProvidedOptions).DeepClone();
        RewriteRefsRecursive(moduleExtractItemSchema, moduleDefName);

        if (moduleOptionsDef["properties"] is JsonObject moduleOptionsDefProperties)
        {
            foreach (KeyValuePair<string, JsonNode?> moduleOption in moduleProvidedOptions["properties"]?.AsObject() ?? Enumerable.Empty<KeyValuePair<string, JsonNode?>>())
            {
                moduleOptionsDefProperties.Add(moduleOption.Key, moduleOption.Value?.DeepClone());
                moduleOptionsOneOf.Add(new JsonObject
                {
                    ["required"] = new JsonArray(moduleOption.Key)
                });
            }
        }

        //JsonObject variant = new()
        //{
        //    ["type"] = "object",
        //    ["additionalProperties"] = false,
        //    ["required"] = new JsonArray(pluginKey),
        //    ["properties"] = new JsonObject
        //    {
        //        [pluginKey] = new JsonObject
        //        {
        //            ["type"] = "object",
        //            ["additionalProperties"] = false,
        //            ["properties"] = new JsonObject
        //            {
        //                ["extracts"] = new JsonObject
        //                {
        //                    ["type"] = "array",
        //                    ["items"] = new JsonObject
        //                    {
        //                        ["oneOf"] = new JsonArray(pluginExtractItemSchema)
        //                    }
        //                }
        //            }
        //        }
        //    }
        //};

        //pluginOptionsOneOf.Add(variant);
    }

    //private static string DerivePluginKey(JsonObject pluginSchema)
    //{
    //    if (pluginSchema["$defs"] is JsonObject defs
    //        && defs["pluginMeta"] is JsonObject meta
    //        && meta["properties"] is JsonObject props
    //        && props["pluginKey"] is JsonObject pluginKeySchema)
    //    {
    //        string? key = pluginKeySchema["const"]?.GetValue<string?>();
    //        if (!string.IsNullOrWhiteSpace(key))
    //        {
    //            return key;
    //        }

    //        if (pluginKeySchema["enum"] is JsonArray arr && arr.Count > 0)
    //        {
    //            string? enumKey = arr[0]?.GetValue<string?>();
    //            if (!string.IsNullOrWhiteSpace(enumKey))
    //            {
    //                return enumKey;
    //            }
    //        }
    //    }

    //    throw new InvalidOperationException("Plugin schema missing $defs.pluginMeta.pluginKey");
    //}

    private static JsonObject ExtractModuleExtractItemSchema(JsonObject moduleProvidedOptions)
    {
        if (moduleProvidedOptions["properties"] is not JsonObject props)
        {
            return moduleProvidedOptions;
        }

        if (props["extracts"] is not JsonObject extracts)
        {
            return moduleProvidedOptions;
        }

        if (extracts["items"] is not JsonObject items)
        {
            return moduleProvidedOptions;
        }

        // If items is already a schema object, return it. (If module uses array schema with oneOf inside, it can still work.)
        return items;
    }

    private static JsonObject RewriteModuleSchemaForEmbedding(JsonObject moduleSchema, string moduleDefName)
    {
        JsonNode clone = moduleSchema.DeepClone();
        RewriteRefsRecursive(clone, moduleDefName);
        return clone as JsonObject ?? [];
    }

    private static void RewriteRefsRecursive(JsonNode node, string moduleDefName)
    {
        if (node is JsonObject obj)
        {
            foreach ((string key, JsonNode? value) in obj.ToList())
            {
                if (key == "$ref" && value is JsonValue v)
                {
                    string? s = v.GetValue<string?>();
                    if (TryRewriteModuleLocalRef(s, moduleDefName, out string? rewritten))
                    {
                        obj[key] = rewritten;
                    }
                    continue;
                }

                if (value is not null)
                {
                    RewriteRefsRecursive(value, moduleDefName);
                }
            }
        }
        else if (node is JsonArray arr)
        {
            foreach (JsonNode? item in arr)
            {
                if (item is not null)
                {
                    RewriteRefsRecursive(item, moduleDefName);
                }
            }
        }
    }

    private static bool TryRewriteModuleLocalRef(string? refValue, string moduleDefName, out string? rewritten)
    {
        rewritten = null;
        if (string.IsNullOrWhiteSpace(refValue))
        {
            return false;
        }

        const string prefix = "#/$defs/";
        if (!refValue.StartsWith(prefix, StringComparison.Ordinal))
        {
            return false;
        }

        string alreadyPrefixed = $"#/$defs/{moduleDefName}/";
        if (refValue.StartsWith(alreadyPrefixed, StringComparison.Ordinal))
        {
            return false;
        }

        // The module schema is embedded under `#/$defs/<moduleDefName>`.
        // Rewrite `#/$defs/x` -> `#/$defs/<moduleDefName>/$defs/x`.
        rewritten = $"#/$defs/{moduleDefName}/$defs/{refValue[prefix.Length..]}";
        return true;
    }

    private static void ApplyFilesOptionsOneOf(JsonObject root, List<string> defNames)
    {
        JsonObject? properties = root["properties"] as JsonObject;
        JsonObject? files = properties?["files"] as JsonObject;
        JsonObject? items = files?["items"] as JsonObject;
        JsonObject? fileProps = items?["properties"] as JsonObject;
        if (fileProps?["options"] is not JsonObject options)
        {
            return;
        }

        JsonArray oneOf = [];

        // allow empty/unspecified options
        oneOf.Add(new JsonObject
        {
            ["type"] = "object",
            ["additionalProperties"] = true
        });

        foreach (string defName in defNames.OrderBy(n => n, StringComparer.OrdinalIgnoreCase))
        {
            oneOf.Add(new JsonObject { ["$ref"] = $"#/$defs/{defName}" });
        }

        options["oneOf"] = oneOf;
        _ = options.Remove("additionalProperties");
    }

    public static string MakeSafeDefName(ISchema schema, JsonObject moduleSchema)
    {
        string? id = moduleSchema["$id"]?.GetValue<string?>();
        return !string.IsNullOrWhiteSpace(id)
            ? Sanitize(id)
            : Sanitize(Path.GetFileNameWithoutExtension(schema.Path));
    }

    private static string Sanitize(string s)
    {
        Span<char> buf = stackalloc char[s.Length];
        int j = 0;
        foreach (char c in s)
        {
            buf[j++] = char.IsLetterOrDigit(c) ? c : '_';
        }
        return new string(buf[..j]);
    }

    public static void Write(JsonObject schema, string path)
    {
        _ = Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, schema.ToJsonString(new JsonSerializerOptions { WriteIndented = true }));
    }
}
