<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ContextCompiler.Configuration.Json\ContextCompiler.Configuration.Json.csproj" />
    <ProjectReference Include="..\ContextCompiler.Core\ContextCompiler.Core.csproj" />
    <ProjectReference Include="..\ContextCompiler.Infrastructure\ContextCompiler.Infrastructure.csproj" />
    <ProjectReference Include="..\ContextCompiler.Mcp.Core\ContextCompiler.Mcp.Core.csproj" />
    <ProjectReference Include="..\ContextCompiler.Mcp.Infrastructure\ContextCompiler.Mcp.Infrastructure.csproj" />
    <ProjectReference Include="..\ContextCompiler.Modules.Loader\ContextCompiler.Modules.Loader.csproj" />
  </ItemGroup>
</Project>
