<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Configurations>Debug;Release;DebugLocal</Configurations>
		<IsPackable>true</IsPackable>
		<PackageId>ContextCompiler.Abstractions</PackageId>
		<Description>
			Package d'abstractions de ContextCompiler.
		</Description>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>

	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'DebugLocal'">
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="System.CommandLine" />
	</ItemGroup>

	<ItemGroup>
		<None Include="LICENSE.txt" Pack="true" PackagePath="" />
		<None Include="README.md" Pack="true" PackagePath="" />
	</ItemGroup>
</Project>
