using ContextCompiler.Abstractions.Output;
using ContextCompiler.Abstractions.Prompt;
using ContextCompiler.Modules.Abstractions;

namespace ContextCompiler.Blueprints.DotNet.WebApp.Razor;

internal sealed class DotNetWebAppRazorBlueprintComposer(
    IPrompt prompt,
    IBlueprintBuilder blueprintBuilder,
    IBlueprintStepBuilder stepBuilder,
    IMustConstraintBuilder mustBuilder,
    IMustNotConstraintBuilder mustNotBuilder,
    IObjectiveBuilder objectiveBuilder,
    IAssumptionBuilder assumptionBuilder,
    IGlossaryTermBuilder glossaryBuilder,
    ICommandBuilder commandBuilder) : IBlueprintComposerModule
{
    public ModuleMetadata Metadata => IGlobalPipelineModule.Meta("blueprints.dotnet.webapp.razor", GlobalPipelineModuleKinds.PromptComposer, priority: 10);

    public Task Run(CancellationToken cancellationToken)
    {
        IBlueprint blueprint = blueprintBuilder
            .InitNew()
            .WithId("dotnet.webapp.razor")
            .WithName("Application Web .NET avec Razor Pages")
            .WithDescription("Blueprint pour construire une application web .NET moderne utilisant Razor Pages avec une architecture propre, sécurisée et maintenable.")

            // === OBJECTIFS ===
            .AddObjective(objectiveBuilder.InitNew()
                .WithName("OBJ1")
                .WithDescription("Créer une application web performante et responsive")
                .Build())
            .AddObjective(objectiveBuilder.InitNew()
                .WithName("OBJ2")
                .WithDescription("Implémenter une architecture en couches avec séparation des responsabilités")
                .Build())
            .AddObjective(objectiveBuilder.InitNew()
                .WithName("OBJ3")
                .WithDescription("Garantir la sécurité de l'application (authentification, autorisation, validation)")
                .Build())
            .AddObjective(objectiveBuilder.InitNew()
                .WithName("OBJ4")
                .WithDescription("Faciliter la maintenance et l'évolutivité du code")
                .Build())

            // === CONTRAINTES GLOBALES ===
            .AddMustConstraint(mustBuilder.InitNew()
                .WithId("MUST1")
                .WithText("Utiliser le modèle Razor Pages (pas MVC)")
                .Build())
            .AddMustConstraint(mustBuilder.InitNew()
                .WithId("MUST2")
                .WithText("Implémenter le pattern PageModel pour chaque page")
                .Build())
            .AddMustConstraint(mustBuilder.InitNew()
                .WithId("MUST3")
                .WithText("Séparer la logique métier dans des services injectés")
                .Build())
            .AddMustConstraint(mustBuilder.InitNew()
                .WithId("MUST4")
                .WithText("Utiliser les Tag Helpers pour les formulaires et validation")
                .Build())
            .AddMustConstraint(mustBuilder.InitNew()
                .WithId("MUST5")
                .WithText("Implémenter la validation côté client et serveur")
                .Build())
            .AddMustConstraint(mustBuilder.InitNew()
                .WithId("MUST6")
                .WithText("Utiliser les ViewModels/InputModels pour la liaison de données")
                .Build())
            .AddMustConstraint(mustBuilder.InitNew()
                .WithId("MUST7")
                .WithText("Configurer HTTPS et HSTS")
                .Build())

            .AddMustNotConstraint(mustNotBuilder.InitNew()
                .WithId("MUSTNOT1")
                .WithText("Mettre la logique métier dans les PageModel")
                .Build())
            .AddMustNotConstraint(mustNotBuilder.InitNew()
                .WithId("MUSTNOT2")
                .WithText("Utiliser ViewBag ou ViewData pour passer des données")
                .Build())
            .AddMustNotConstraint(mustNotBuilder.InitNew()
                .WithId("MUSTNOT3")
                .WithText("Exposer directement les entités de base de données dans les pages")
                .Build())
            .AddMustNotConstraint(mustNotBuilder.InitNew()
                .WithId("MUSTNOT4")
                .WithText("Stocker des secrets dans appsettings.json")
                .Build())

            // === ASSUMPTIONS ===
            .AddAssumption(assumptionBuilder.InitNew()
                .WithName("AS1")
                .WithDescription(".NET SDK 10 ou supérieur est installé")
                .Build())
            .AddAssumption(assumptionBuilder.InitNew()
                .WithName("AS2")
                .WithDescription("L'environnement de développement supporte HTTPS")
                .Build())
            .AddAssumption(assumptionBuilder.InitNew()
                .WithName("AS3")
                .WithDescription("Une base de données est disponible (SQL Server, PostgreSQL, ou autre)")
                .Build())

            // === GLOSSAIRE ===
            .AddGlossaryTerm(glossaryBuilder.InitNew()
                .WithTerm("Razor Pages")
                .WithDefinition("Un framework de pages web dans ASP.NET Core qui utilise le modèle MVVM côté serveur")
                .Build())
            .AddGlossaryTerm(glossaryBuilder.InitNew()
                .WithTerm("PageModel")
                .WithDefinition("Classe C# qui contient les gestionnaires et la logique pour une page Razor")
                .Build())
            .AddGlossaryTerm(glossaryBuilder.InitNew()
                .WithTerm("Tag Helpers")
                .WithDefinition("Composants côté serveur qui participent à la création et au rendu d'éléments HTML dans les fichiers Razor")
                .Build())
            .AddGlossaryTerm(glossaryBuilder.InitNew()
                .WithTerm("ViewModels")
                .WithDefinition("Classes qui représentent les données affichées dans une vue")
                .Build())
            .AddGlossaryTerm(glossaryBuilder.InitNew()
                .WithTerm("InputModels")
                .WithDefinition("Classes qui représentent les données soumises par l'utilisateur via un formulaire")
                .Build())
            .AddGlossaryTerm(glossaryBuilder.InitNew()
                .WithTerm("Layout")
                .WithDefinition("Page Razor partagée qui définit la structure commune de l'application")
                .Build())
            .AddGlossaryTerm(glossaryBuilder.InitNew()
                .WithTerm("Partial View")
                .WithDefinition("Fragment de vue Razor réutilisable qui peut être inclus dans d'autres vues")
                .Build())
            .AddGlossaryTerm(glossaryBuilder.InitNew()
                .WithTerm("CSRF")
                .WithDefinition("Cross-Site Request Forgery - type d'attaque que Razor Pages protège automatiquement via les tokens anti-forgery")
                .Build())

            // === COMMANDES ===
            .AddCommand(commandBuilder.InitNew()
                .WithName("create-project")
                .WithDescription("Créer un nouveau projet Razor Pages avec dotnet new webapp")
                .Build())
            .AddCommand(commandBuilder.InitNew()
                .WithName("add-page")
                .WithDescription("Ajouter une nouvelle page Razor avec son PageModel")
                .Build())
            .AddCommand(commandBuilder.InitNew()
                .WithName("add-service")
                .WithDescription("Ajouter un nouveau service et l'enregistrer dans DI")
                .Build())
            .AddCommand(commandBuilder.InitNew()
                .WithName("add-authentication")
                .WithDescription("Configurer l'authentification (Identity, OAuth, etc.)")
                .Build())
            .AddCommand(commandBuilder.InitNew()
                .WithName("add-database")
                .WithDescription("Configurer Entity Framework Core et créer le DbContext")
                .Build())

            // === STEPS ===
            .AddStep(stepBuilder.InitNew()
                .WithContent("Initialisation du projet\n\nCréer le projet avec la commande `dotnet new webapp -n MonProjet` et configurer la structure de base.")
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP1_MUST1")
                    .WithText("Créer un fichier .gitignore adapté à .NET")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP1_MUST2")
                    .WithText("Configurer launchSettings.json avec HTTPS")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP1_MUST3")
                    .WithText("Créer la structure de dossiers : Pages/, Services/, Models/, Data/")
                    .Build())
                .Build())

            .AddStep(stepBuilder.InitNew()
                .WithContent("Configuration de Program.cs\n\nConfigurer les services, middleware et pipeline de requêtes dans Program.cs.")
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP2_MUST1")
                    .WithText("Enregistrer tous les services dans le conteneur DI")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP2_MUST2")
                    .WithText("Configurer app.UseHttpsRedirection() et app.UseHsts()")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP2_MUST3")
                    .WithText("Configurer app.UseStaticFiles() pour les ressources statiques")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP2_MUST4")
                    .WithText("Configurer app.UseRouting() et app.MapRazorPages()")
                    .Build())
                .AddMustNotConstraint(mustNotBuilder.InitNew()
                    .WithId("STEP2_MUSTNOT1")
                    .WithText("Enregistrer les services directement dans le code au lieu du conteneur DI")
                    .Build())
                .Build())

            .AddStep(stepBuilder.InitNew()
                .WithContent("Création du Layout et pages partagées\n\nCréer _Layout.cshtml, _ViewStart.cshtml et _ViewImports.cshtml pour définir la structure commune.")
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP3_MUST1")
                    .WithText("Créer Pages/Shared/_Layout.cshtml avec la structure HTML de base")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP3_MUST2")
                    .WithText("Créer Pages/_ViewStart.cshtml pour définir le layout par défaut")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP3_MUST3")
                    .WithText("Créer Pages/_ViewImports.cshtml pour les using et Tag Helpers globaux")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP3_MUST4")
                    .WithText("Inclure @addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers dans _ViewImports")
                    .Build())
                .Build())

            .AddStep(stepBuilder.InitNew()
                .WithContent("Création des pages Razor\n\nCréer les pages Razor (.cshtml) avec leurs PageModel (.cshtml.cs) correspondants.")
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP4_MUST1")
                    .WithText("Créer une page avec @page directive en haut")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP4_MUST2")
                    .WithText("Créer le PageModel hérité de PageModel base class")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP4_MUST3")
                    .WithText("Utiliser @model directive pour lier la page à son PageModel")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP4_MUST4")
                    .WithText("Implémenter OnGet/OnPost pour les gestionnaires de requêtes HTTP")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP4_MUST5")
                    .WithText("Utiliser [BindProperty] pour la liaison de données dans les POST")
                    .Build())
                .AddMustNotConstraint(mustNotBuilder.InitNew()
                    .WithId("STEP4_MUSTNOT1")
                    .WithText("Accéder directement à HttpContext.Request.Form dans les handlers")
                    .Build())
                .Build())

            .AddStep(stepBuilder.InitNew()
                .WithContent("Implémentation des services\n\nCréer les services métier et les enregistrer dans le conteneur d'injection de dépendances.")
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP5_MUST1")
                    .WithText("Créer des interfaces pour chaque service")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP5_MUST2")
                    .WithText("Implémenter les services dans des classes dédiées")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP5_MUST3")
                    .WithText("Injecter les services via le constructeur des PageModel")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP5_MUST4")
                    .WithText("Enregistrer les services avec le scope approprié (Scoped, Transient, Singleton)")
                    .Build())
                .AddMustNotConstraint(mustNotBuilder.InitNew()
                    .WithId("STEP5_MUSTNOT1")
                    .WithText("Instancier les services manuellement avec 'new' dans les PageModel")
                    .Build())
                .Build())

            .AddStep(stepBuilder.InitNew()
                .WithContent("Configuration de la validation\n\nMettre en place la validation des données avec Data Annotations et validation côté client.")
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP6_MUST1")
                    .WithText("Utiliser Data Annotations sur les InputModels ([Required], [StringLength], etc.)")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP6_MUST2")
                    .WithText("Vérifier ModelState.IsValid avant de traiter les données POST")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP6_MUST3")
                    .WithText("Utiliser <div asp-validation-summary> pour afficher les erreurs")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP6_MUST4")
                    .WithText("Utiliser <span asp-validation-for> pour les erreurs de champ")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP6_MUST5")
                    .WithText("Inclure jQuery Validation pour la validation côté client")
                    .Build())
                .Build())

            .AddStep(stepBuilder.InitNew()
                .WithContent("Gestion des données avec Entity Framework Core\n\nConfigurer EF Core, créer le DbContext et implémenter les repositories si nécessaire.")
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP7_MUST1")
                    .WithText("Créer un DbContext dédié dans le dossier Data/")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP7_MUST2")
                    .WithText("Configurer la chaîne de connexion dans appsettings.json")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP7_MUST3")
                    .WithText("Enregistrer le DbContext avec AddDbContext dans Program.cs")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP7_MUST4")
                    .WithText("Utiliser les migrations EF Core pour gérer le schéma de base de données")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP7_MUST5")
                    .WithText("Créer des entités avec des propriétés de navigation appropriées")
                    .Build())
                .AddMustNotConstraint(mustNotBuilder.InitNew()
                    .WithId("STEP7_MUSTNOT1")
                    .WithText("Injecter DbContext directement dans les PageModel (utiliser des repositories ou services)")
                    .Build())
                .Build())

            .AddStep(stepBuilder.InitNew()
                .WithContent("Implémentation de l'authentification et autorisation\n\nConfigurer ASP.NET Core Identity ou un système d'authentification personnalisé.")
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP8_MUST1")
                    .WithText("Configurer Identity avec AddIdentity ou AddDefaultIdentity")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP8_MUST2")
                    .WithText("Ajouter app.UseAuthentication() avant app.UseAuthorization() dans le pipeline")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP8_MUST3")
                    .WithText("Utiliser [Authorize] et [AllowAnonymous] pour contrôler l'accès aux pages")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP8_MUST4")
                    .WithText("Créer des pages Login et Logout dans Pages/Account/")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP8_MUST5")
                    .WithText("Hacher les mots de passe avec Identity PasswordHasher")
                    .Build())
                .AddMustNotConstraint(mustNotBuilder.InitNew()
                    .WithId("STEP8_MUSTNOT1")
                    .WithText("Stocker les mots de passe en clair ou avec un hachage faible")
                    .Build())
                .Build())

            .AddStep(stepBuilder.InitNew()
                .WithContent("Gestion des ressources statiques et assets\n\nOrganiser et optimiser les fichiers CSS, JavaScript et images.")
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP9_MUST1")
                    .WithText("Placer les fichiers statiques dans wwwroot/")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP9_MUST2")
                    .WithText("Organiser les assets : wwwroot/css/, wwwroot/js/, wwwroot/images/")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP9_MUST3")
                    .WithText("Utiliser des CDN ou bundling/minification pour la production")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP9_MUST4")
                    .WithText("Inclure site.css pour les styles personnalisés")
                    .Build())
                .Build())

            .AddStep(stepBuilder.InitNew()
                .WithContent("Gestion des erreurs et logging\n\nImplémenter une gestion robuste des erreurs et du logging.")
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP10_MUST1")
                    .WithText("Créer une page Error.cshtml avec son ErrorModel")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP10_MUST2")
                    .WithText("Configurer app.UseExceptionHandler(\"/Error\") en production")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP10_MUST3")
                    .WithText("Configurer app.UseDeveloperExceptionPage() en développement")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP10_MUST4")
                    .WithText("Utiliser ILogger dans les PageModel et services")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP10_MUST5")
                    .WithText("Configurer le logging dans appsettings.json (niveau, providers)")
                    .Build())
                .Build())

            .AddStep(stepBuilder.InitNew()
                .WithContent("Formulaires et liaison de données\n\nImplémenter des formulaires avec Tag Helpers et liaison de données sécurisée.")
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP11_MUST1")
                    .WithText("Utiliser <form method=\"post\"> avec asp-page pour les formulaires")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP11_MUST2")
                    .WithText("Utiliser asp-for sur les inputs pour la liaison automatique")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP11_MUST3")
                    .WithText("Inclure @Html.AntiForgeryToken() ou utiliser <form> qui l'ajoute automatiquement")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP11_MUST4")
                    .WithText("Utiliser [ValidateAntiForgeryToken] implicitement activé sur les POST")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP11_MUST5")
                    .WithText("Retourner RedirectToPage() après un POST réussi (pattern Post-Redirect-Get)")
                    .Build())
                .Build())

            .AddStep(stepBuilder.InitNew()
                .WithContent("Configuration de la sécurité\n\nAppliquer les bonnes pratiques de sécurité web.")
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP12_MUST1")
                    .WithText("Activer HTTPS Redirection et HSTS")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP12_MUST2")
                    .WithText("Configurer les en-têtes de sécurité (X-Frame-Options, X-Content-Type-Options)")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP12_MUST3")
                    .WithText("Utiliser User Secrets pour le développement local")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP12_MUST4")
                    .WithText("Utiliser Azure Key Vault ou variables d'environnement en production")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP12_MUST5")
                    .WithText("Encoder toutes les sorties HTML avec @ pour éviter XSS")
                    .Build())
                .AddMustNotConstraint(mustNotBuilder.InitNew()
                    .WithId("STEP12_MUSTNOT1")
                    .WithText("Utiliser @Html.Raw() sauf si absolument nécessaire et avec validation")
                    .Build())
                .Build())

            .AddStep(stepBuilder.InitNew()
                .WithContent("Tests et validation\n\nCréer des tests unitaires et d'intégration pour valider le comportement.")
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP13_MUST1")
                    .WithText("Créer un projet de test avec dotnet new xunit")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP13_MUST2")
                    .WithText("Tester les services avec des tests unitaires")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP13_MUST3")
                    .WithText("Tester les PageModel avec des mocks des dépendances")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP13_MUST4")
                    .WithText("Utiliser WebApplicationFactory pour les tests d'intégration")
                    .Build())
                .Build())

            .AddStep(stepBuilder.InitNew()
                .WithContent("Déploiement et configuration\n\nPréparer l'application pour le déploiement.")
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP14_MUST1")
                    .WithText("Configurer différents appsettings par environnement (Development, Staging, Production)")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP14_MUST2")
                    .WithText("Utiliser appsettings.{Environment}.json pour les surcharges")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP14_MUST3")
                    .WithText("Configurer CORS si l'API est appelée depuis d'autres domaines")
                    .Build())
                .AddMustConstraint(mustBuilder.InitNew()
                    .WithId("STEP14_MUST4")
                    .WithText("Publier avec dotnet publish -c Release")
                    .Build())
                .AddMustNotConstraint(mustNotBuilder.InitNew()
                    .WithId("STEP14_MUSTNOT1")
                    .WithText("Déployer avec des secrets ou connexions strings en clair dans appsettings.json")
                    .Build())
                .Build())

            .Build();

        prompt.Blueprints = [.. prompt.Blueprints, blueprint];

        return Task.CompletedTask;
    }
}
