using System.Globalization;
using System.Text;
using System.Text.Json;

using ContextCompiler.Abstractions.Pipelines;
using ContextCompiler.Abstractions.Pipelines.Events;

namespace ContextCompiler.Reports.Modules.Pipelines.Mermaid;

internal static class InteractiveMermaidHtmlGenerator
{
    public static string GenerateHtml(IReadOnlyList<IPipelineEvent> events, string title = "Pipeline Execution Report - Interactive")
    {
        StringBuilder sb = new();

        // Serialize events to JSON for JavaScript
        string eventsJson = JsonSerializer.Serialize(events.Select(e =>
        {
            string? parentPipelineId = null;
            if (e.RunContext is ISubPipelineRunContext subContext)
            {
                parentPipelineId = subContext.Parent.Pipeline.Id;
            }

            return new
            {
                e.Name,
                PipelineId = e.RunContext.Pipeline.Id,
                PipelineCurrentPhaseKey = e.RunContext.PhaseKey,
                ParentPipelineId = parentPipelineId,
                e.PhaseId,
                e.ModuleId,
                e.ItemId,
                Timestamp = e.Timestamp.ToString("o"),
                Duration = e is PhaseCompleted completed ? completed.Duration.TotalMilliseconds : (double?)null,
                Error = e is PhaseFailed failed ? failed.Exception.Message : null
            };
        }));

        _ = sb.AppendLine("<!DOCTYPE html>")
              .AppendLine("<html lang=\"en\">")
              .AppendLine("<head>")
              .AppendLine("    <meta charset=\"UTF-8\">")
              .AppendLine("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">")
              .AppendLine(CultureInfo.InvariantCulture, $"    <title>{title}</title>")
              .AppendLine("    <script type=\"module\">")
              .AppendLine("        import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';")
              .AppendLine("        window.mermaid = mermaid;")
              .AppendLine("        mermaid.initialize({ ")
              .AppendLine("            startOnLoad: false,")
              .AppendLine("            theme: 'default',")
              .AppendLine("            maxTextSize: 200000,")
              .AppendLine("            maxEdges: 2000,")
              .AppendLine("            flowchart: {")
              .AppendLine("                useMaxWidth: true,")
              .AppendLine("                htmlLabels: true,")
              .AppendLine("                curve: 'basis'")
              .AppendLine("            }")
              .AppendLine("        });")
              .AppendLine("    </script>")
              .AppendLine("    <style>")
              .AppendLine("        body {")
              .AppendLine("            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;")
              .AppendLine("            margin: 0;")
              .AppendLine("            padding: 20px;")
              .AppendLine("            background: #f5f5f5;")
              .AppendLine("        }")
              .AppendLine("        .container {")
              .AppendLine("            max-width: 1600px;")
              .AppendLine("            margin: 0 auto;")
              .AppendLine("            background: white;")
              .AppendLine("            padding: 30px;")
              .AppendLine("            border-radius: 8px;")
              .AppendLine("            box-shadow: 0 2px 4px rgba(0,0,0,0.1);")
              .AppendLine("        }")
              .AppendLine("        h1 {")
              .AppendLine("            color: #333;")
              .AppendLine("            margin-top: 0;")
              .AppendLine("            border-bottom: 3px solid #01579b;")
              .AppendLine("            padding-bottom: 10px;")
              .AppendLine("        }")
              .AppendLine("        .filters {")
              .AppendLine("            background: #f9f9f9;")
              .AppendLine("            border: 1px solid #ddd;")
              .AppendLine("            border-radius: 4px;")
              .AppendLine("            padding: 20px;")
              .AppendLine("            margin-bottom: 20px;")
              .AppendLine("        }")
              .AppendLine("        .filters h3 {")
              .AppendLine("            margin-top: 0;")
              .AppendLine("            color: #555;")
              .AppendLine("        }")
              .AppendLine("        .filter-group {")
              .AppendLine("            display: inline-block;")
              .AppendLine("            margin-right: 20px;")
              .AppendLine("            margin-bottom: 10px;")
              .AppendLine("        }")
              .AppendLine("        .filter-group label {")
              .AppendLine("            display: block;")
              .AppendLine("            font-weight: 600;")
              .AppendLine("            margin-bottom: 5px;")
              .AppendLine("            color: #555;")
              .AppendLine("        }")
              .AppendLine("        .filter-group select {")
              .AppendLine("            padding: 8px 12px;")
              .AppendLine("            border: 1px solid #ccc;")
              .AppendLine("            border-radius: 4px;")
              .AppendLine("            background: white;")
              .AppendLine("            font-size: 14px;")
              .AppendLine("            min-width: 200px;")
              .AppendLine("        }")
              .AppendLine("        .filter-actions {")
              .AppendLine("            margin-top: 15px;")
              .AppendLine("        }")
              .AppendLine("        .filter-actions button {")
              .AppendLine("            padding: 10px 20px;")
              .AppendLine("            margin-right: 10px;")
              .AppendLine("            border: none;")
              .AppendLine("            border-radius: 4px;")
              .AppendLine("            font-size: 14px;")
              .AppendLine("            cursor: pointer;")
              .AppendLine("            font-weight: 600;")
              .AppendLine("        }")
              .AppendLine("        .btn-apply {")
              .AppendLine("            background: #01579b;")
              .AppendLine("            color: white;")
              .AppendLine("        }")
              .AppendLine("        .btn-apply:hover {")
              .AppendLine("            background: #014078;")
              .AppendLine("        }")
              .AppendLine("        .btn-reset {")
              .AppendLine("            background: #757575;")
              .AppendLine("            color: white;")
              .AppendLine("        }")
              .AppendLine("        .btn-reset:hover {")
              .AppendLine("            background: #616161;")
              .AppendLine("        }")
              .AppendLine("        .info-box {")
              .AppendLine("            background: #e3f2fd;")
              .AppendLine("            border: 1px solid #01579b;")
              .AppendLine("            border-radius: 4px;")
              .AppendLine("            padding: 15px;")
              .AppendLine("            margin-bottom: 20px;")
              .AppendLine("        }")
              .AppendLine("        .info-box p {")
              .AppendLine("            margin: 5px 0;")
              .AppendLine("            color: #01579b;")
              .AppendLine("        }")
              .AppendLine("        .zoom-controls {")
              .AppendLine("            margin: 20px 0 10px 0;")
              .AppendLine("            display: flex;")
              .AppendLine("            align-items: center;")
              .AppendLine("            gap: 10px;")
              .AppendLine("            background: #f9f9f9;")
              .AppendLine("            padding: 10px 15px;")
              .AppendLine("            border-radius: 4px;")
              .AppendLine("            border: 1px solid #ddd;")
              .AppendLine("        }")
              .AppendLine("        .zoom-controls button {")
              .AppendLine("            padding: 8px 16px;")
              .AppendLine("            border: none;")
              .AppendLine("            border-radius: 4px;")
              .AppendLine("            font-size: 16px;")
              .AppendLine("            font-weight: bold;")
              .AppendLine("            cursor: pointer;")
              .AppendLine("            background: #01579b;")
              .AppendLine("            color: white;")
              .AppendLine("            transition: background 0.2s;")
              .AppendLine("        }")
              .AppendLine("        .zoom-controls button:hover {")
              .AppendLine("            background: #014078;")
              .AppendLine("        }")
              .AppendLine("        .zoom-controls button:disabled {")
              .AppendLine("            background: #ccc;")
              .AppendLine("            cursor: not-allowed;")
              .AppendLine("        }")
              .AppendLine("        .zoom-level {")
              .AppendLine("            font-weight: 600;")
              .AppendLine("            color: #333;")
              .AppendLine("            min-width: 60px;")
              .AppendLine("            text-align: center;")
              .AppendLine("        }")
              .AppendLine("        .mermaid-container {")
              .AppendLine("            margin: 10px 0 20px 0;")
              .AppendLine("            overflow: auto;")
              .AppendLine("            border: 1px solid #ddd;")
              .AppendLine("            border-radius: 4px;")
              .AppendLine("            padding: 20px;")
              .AppendLine("            background: white;")
              .AppendLine("            position: relative;")
              .AppendLine("            min-height: 600px;")
              .AppendLine("            height: 80vh;")
              .AppendLine("        }")
              .AppendLine("        #mermaidDiagram {")
              .AppendLine("            text-align: center;")
              .AppendLine("            transform-origin: top left;")
              .AppendLine("            transition: transform 0.2s ease-out;")
              .AppendLine("        }")
              .AppendLine("        .legend {")
              .AppendLine("            margin-top: 30px;")
              .AppendLine("            padding: 15px;")
              .AppendLine("            background: #f9f9f9;")
              .AppendLine("            border-radius: 4px;")
              .AppendLine("        }")
              .AppendLine("        .legend h3 {")
              .AppendLine("            margin-top: 0;")
              .AppendLine("            color: #555;")
              .AppendLine("        }")
              .AppendLine("        .legend-item {")
              .AppendLine("            display: inline-block;")
              .AppendLine("            margin-right: 20px;")
              .AppendLine("            margin-bottom: 10px;")
              .AppendLine("        }")
              .AppendLine("        .legend-box {")
              .AppendLine("            display: inline-block;")
              .AppendLine("            width: 20px;")
              .AppendLine("            height: 20px;")
              .AppendLine("            margin-right: 8px;")
              .AppendLine("            vertical-align: middle;")
              .AppendLine("            border-radius: 3px;")
              .AppendLine("        }")
              .AppendLine("        .started { background: #e1f5fe; border: 2px solid #01579b; }")
              .AppendLine("        .completed { background: #c8e6c9; border: 2px solid #2e7d32; }")
              .AppendLine("        .failed { background: #ffcdd2; border: 2px solid #c62828; }")
              .AppendLine("        .timestamp {")
              .AppendLine("            color: #666;")
              .AppendLine("            font-size: 0.9em;")
              .AppendLine("            margin-top: 20px;")
              .AppendLine("        }")
              .AppendLine("        .loading {")
              .AppendLine("            text-align: center;")
              .AppendLine("            padding: 40px;")
              .AppendLine("            color: #666;")
              .AppendLine("        }")
              .AppendLine("    </style>")
              .AppendLine("</head>")
              .AppendLine("<body>")
              .AppendLine("    <div class=\"container\">")
              .AppendLine(CultureInfo.InvariantCulture, $"        <h1>{title}</h1>")
              .AppendLine("        <div class=\"filters\">")
              .AppendLine("            <h3>🔍 Filters - Select what to visualize</h3>")
              .AppendLine("            <div class=\"filter-group\">")
              .AppendLine("                <label for=\"pipelineFilter\">Pipeline:</label>")
              .AppendLine("                <select id=\"pipelineFilter\">")
              .AppendLine("                    <option value=\"\">All Pipelines</option>")
              .AppendLine("                </select>")
              .AppendLine("            </div>")
              .AppendLine("            <div class=\"filter-group\">")
              .AppendLine("                <label for=\"phaseFilter\">Phase:</label>")
              .AppendLine("                <select id=\"phaseFilter\">")
              .AppendLine("                    <option value=\"\">All Phases</option>")
              .AppendLine("                </select>")
              .AppendLine("            </div>")
              .AppendLine("            <div class=\"filter-group\">")
              .AppendLine("                <label for=\"moduleFilter\">Module:</label>")
              .AppendLine("                <select id=\"moduleFilter\">")
              .AppendLine("                    <option value=\"\">All Modules</option>")
              .AppendLine("                </select>")
              .AppendLine("            </div>")
              .AppendLine("            <div class=\"filter-group\">")
              .AppendLine("                <label for=\"itemFilter\">Item:</label>")
              .AppendLine("                <select id=\"itemFilter\">")
              .AppendLine("                    <option value=\"\">All Items</option>")
              .AppendLine("                </select>")
              .AppendLine("            </div>")
              .AppendLine("            <div class=\"filter-actions\">")
              .AppendLine("                <button class=\"btn-apply\" onclick=\"applyFilters()\">Apply Filters</button>")
              .AppendLine("                <button class=\"btn-reset\" onclick=\"resetFilters()\">Reset All</button>")
              .AppendLine("            </div>")
              .AppendLine("            <div style=\"margin-top: 15px; padding-top: 15px; border-top: 1px solid #ddd;\">")
              .AppendLine("                <label style=\"display: flex; align-items: center; cursor: pointer; margin-bottom: 10px;\">")
              .AppendLine("                    <input type=\"checkbox\" id=\"showPipelineLinks\" checked style=\"margin-right: 8px;\">")
              .AppendLine("                    <span style=\"font-weight: 600;\">Show pipeline hierarchy links</span>")
              .AppendLine("                </label>")
              .AppendLine("                <label style=\"display: flex; align-items: center; cursor: pointer; margin-bottom: 10px;\">")
              .AppendLine("                    <input type=\"checkbox\" id=\"groupByItem\" checked style=\"margin-right: 8px;\">")
              .AppendLine("                    <span style=\"font-weight: 600;\">Group by Item (shows file journey)</span>")
              .AppendLine("                </label>")
              .AppendLine("                <label style=\"display: flex; align-items: center; cursor: pointer; margin-bottom: 10px;\">")
              .AppendLine("                    <input type=\"checkbox\" id=\"showPipelineId\" style=\"margin-right: 8px;\">")
              .AppendLine("                    <span style=\"font-weight: 600;\">Show Pipeline ID in labels (helps identify duplicates)</span>")
              .AppendLine("                </label>")
              .AppendLine("                <div style=\"margin-top: 15px; padding-top: 15px; border-top: 1px solid #ddd;\">")
              .AppendLine("                    <div style=\"font-weight: 600; margin-bottom: 8px;\">Graph Orientation:</div>")
              .AppendLine("                    <label style=\"display: inline-flex; align-items: center; cursor: pointer; margin-right: 20px;\">")
              .AppendLine("                        <input type=\"radio\" name=\"orientation\" id=\"orientationLR\" checked style=\"margin-right: 8px;\">")
              .AppendLine("                        <span>Horizontal (Left → Right) - Recommended for long pipelines</span>")
              .AppendLine("                    </label>")
              .AppendLine("                    <label style=\"display: inline-flex; align-items: center; cursor: pointer;\">")
              .AppendLine("                        <input type=\"radio\" name=\"orientation\" id=\"orientationTD\" style=\"margin-right: 8px;\">")
              .AppendLine("                        <span>Vertical (Top → Bottom)</span>")
              .AppendLine("                    </label>")
              .AppendLine("                </div>")
              .AppendLine("            </div>")
              .AppendLine("        </div>")
              .AppendLine("        <div class=\"info-box\" id=\"infoBox\">")
              .AppendLine(CultureInfo.InvariantCulture, $"            <p><strong>Total events:</strong> <span id=\"eventCount\">{events.Count}</span></p>")
              .AppendLine("            <p><strong>Filtered events:</strong> <span id=\"filteredCount\">0</span></p>")
              .AppendLine("        </div>")
              .AppendLine("        <div class=\"zoom-controls\">")
              .AppendLine("            <button id=\"zoomOut\" title=\"Zoom Out\">➖</button>")
              .AppendLine("            <span class=\"zoom-level\" id=\"zoomLevel\">100%</span>")
              .AppendLine("            <button id=\"zoomIn\" title=\"Zoom In\">➕</button>")
              .AppendLine("            <button id=\"zoomReset\" title=\"Reset Zoom\" style=\"margin-left: 10px;\">Reset</button>")
              .AppendLine("            <span style=\"margin-left: 15px; color: #666; font-size: 0.9em;\">💡 Tip: Use Ctrl+Mouse Wheel or pinch to zoom</span>")
              .AppendLine("        </div>")
              .AppendLine("        <div class=\"mermaid-container\" id=\"mermaidContainer\">")
              .AppendLine("            <div id=\"mermaidDiagram\" class=\"loading\">Loading diagram...</div>")
              .AppendLine("        </div>")
              .AppendLine("        <div class=\"legend\">")
              .AppendLine("            <h3>Legend</h3>")
              .AppendLine("            <div style=\"margin-bottom: 15px;\">")
              .AppendLine("                <strong>Pipelines (colors):</strong>")
              .AppendLine("                <div id=\"pipelineLegend\" style=\"margin-top: 8px;\"></div>")
              .AppendLine("            </div>")
              .AppendLine("            <div>")
              .AppendLine("                <strong>Status:</strong>")
              .AppendLine("                <div style=\"margin-top: 8px;\">")
              .AppendLine("                    <div class=\"legend-item\">")
              .AppendLine("                        <span class=\"legend-box\" style=\"background: #e3f2fd; border: 2px solid #01579b;\"></span>")
              .AppendLine("                        <span>✓ Phase Completed</span>")
              .AppendLine("                    </div>")
              .AppendLine("                    <div class=\"legend-item\">")
              .AppendLine("                        <span class=\"legend-box\" style=\"background: #e3f2fd; border: 2px dashed #01579b;\"></span>")
              .AppendLine("                        <span>Phase Started (orphan)</span>")
              .AppendLine("                    </div>")
              .AppendLine("                    <div class=\"legend-item\">")
              .AppendLine("                        <span class=\"legend-box failed\"></span>")
              .AppendLine("                        <span>✗ Phase Failed</span>")
              .AppendLine("                    </div>")
              .AppendLine("                </div>")
              .AppendLine("            </div>")
              .AppendLine("        </div>")
              .AppendLine(CultureInfo.InvariantCulture, $"        <div class=\"timestamp\">Generated: {DateTimeOffset.UtcNow:yyyy-MM-dd HH:mm:ss} UTC</div>")
              .AppendLine("    </div>")
              .AppendLine("    <script>")
              .AppendLine(CultureInfo.InvariantCulture, $"        const allEvents = {eventsJson};")
              .AppendLine("        let filteredEvents = [...allEvents];")
              .AppendLine("")
              .AppendLine("        function sanitizeId(id) {")
              .AppendLine("            return id.replace(/[-\\.\\s\\/\\(\\)\\[\\]\\{\\}<>:;,?!@#$%^&*+=|\\\\`~\"']/g, '_');")
              .AppendLine("        }")
              .AppendLine("")
              .AppendLine("        function populateFilters() {")
              .AppendLine("            const pipelines = [...new Set(allEvents.map(e => e.PipelineId))];")
              .AppendLine("            const phases = [...new Set(allEvents.map(e => e.PhaseId))];")
              .AppendLine("            const modules = [...new Set(allEvents.map(e => e.ModuleId).filter(m => m))];")
              .AppendLine("            const items = [...new Set(allEvents.map(e => e.ItemId).filter(i => i))];")
              .AppendLine("")
              .AppendLine("            const pipelineSelect = document.getElementById('pipelineFilter');")
              .AppendLine("            pipelines.forEach(p => {")
              .AppendLine("                const option = document.createElement('option');")
              .AppendLine("                option.value = p;")
              .AppendLine("                option.textContent = p;")
              .AppendLine("                pipelineSelect.appendChild(option);")
              .AppendLine("            });")
              .AppendLine("")
              .AppendLine("            const phaseSelect = document.getElementById('phaseFilter');")
              .AppendLine("            phases.forEach(p => {")
              .AppendLine("                const option = document.createElement('option');")
              .AppendLine("                option.value = p;")
              .AppendLine("                option.textContent = p;")
              .AppendLine("                phaseSelect.appendChild(option);")
              .AppendLine("            });")
              .AppendLine("")
              .AppendLine("            const moduleSelect = document.getElementById('moduleFilter');")
              .AppendLine("            modules.forEach(m => {")
              .AppendLine("                const option = document.createElement('option');")
              .AppendLine("                option.value = m;")
              .AppendLine("                option.textContent = m;")
              .AppendLine("                moduleSelect.appendChild(option);")
              .AppendLine("            });")
              .AppendLine("")
              .AppendLine("            const itemSelect = document.getElementById('itemFilter');")
              .AppendLine("            items.forEach(i => {")
              .AppendLine("                const option = document.createElement('option');")
              .AppendLine("                option.value = i;")
              .AppendLine("                option.textContent = i;")
              .AppendLine("                itemSelect.appendChild(option);")
              .AppendLine("            });")
              .AppendLine("")
              .AppendLine("            // Populate pipeline legend")
              .AppendLine("            const pipelineColors = [")
              .AppendLine("                { border: '#01579b', bg: '#e3f2fd', name: 'Blue' },")
              .AppendLine("                { border: '#6a1b9a', bg: '#f3e5f5', name: 'Purple' },")
              .AppendLine("                { border: '#c62828', bg: '#ffebee', name: 'Red' },")
              .AppendLine("                { border: '#2e7d32', bg: '#e8f5e9', name: 'Green' },")
              .AppendLine("                { border: '#f57c00', bg: '#fff3e0', name: 'Orange' },")
              .AppendLine("                { border: '#0277bd', bg: '#e1f5fe', name: 'Cyan' },")
              .AppendLine("                { border: '#5d4037', bg: '#efebe9', name: 'Brown' },")
              .AppendLine("                { border: '#d32f2f', bg: '#fce4ec', name: 'Pink' }")
              .AppendLine("            ];")
              .AppendLine("")
              .AppendLine("            const pipelineLegendDiv = document.getElementById('pipelineLegend');")
              .AppendLine("            pipelines.forEach((pipeline, idx) => {")
              .AppendLine("                const color = pipelineColors[idx % pipelineColors.length];")
              .AppendLine("                const legendItem = document.createElement('div');")
              .AppendLine("                legendItem.className = 'legend-item';")
              .AppendLine("                legendItem.style.marginBottom = '5px';")
              .AppendLine("                ")
              .AppendLine("                const box = document.createElement('span');")
              .AppendLine("                box.className = 'legend-box';")
              .AppendLine("                box.style.background = color.bg;")
              .AppendLine("                box.style.border = `2px solid ${color.border}`;")
              .AppendLine("                ")
              .AppendLine("                const text = document.createElement('span');")
              .AppendLine("                text.textContent = pipeline;")
              .AppendLine("                ")
              .AppendLine("                legendItem.appendChild(box);")
              .AppendLine("                legendItem.appendChild(text);")
              .AppendLine("                pipelineLegendDiv.appendChild(legendItem);")
              .AppendLine("            });")
              .AppendLine("        }")
              .AppendLine("")
              .AppendLine("        function applyFilters() {")
              .AppendLine("            const pipelineFilter = document.getElementById('pipelineFilter').value;")
              .AppendLine("            const phaseFilter = document.getElementById('phaseFilter').value;")
              .AppendLine("            const moduleFilter = document.getElementById('moduleFilter').value;")
              .AppendLine("            const itemFilter = document.getElementById('itemFilter').value;")
              .AppendLine("")
              .AppendLine("            filteredEvents = allEvents.filter(e => {")
              .AppendLine("                if (pipelineFilter && e.PipelineId !== pipelineFilter) return false;")
              .AppendLine("                if (phaseFilter && e.PhaseId !== phaseFilter) return false;")
              .AppendLine("                if (moduleFilter && e.ModuleId !== moduleFilter) return false;")
              .AppendLine("                if (itemFilter && e.ItemId !== itemFilter) return false;")
              .AppendLine("                return true;")
              .AppendLine("            });")
              .AppendLine("")
              .AppendLine("            document.getElementById('filteredCount').textContent = filteredEvents.length;")
              .AppendLine("            generateDiagram();")
              .AppendLine("        }")
              .AppendLine("")
              .AppendLine("        function resetFilters() {")
              .AppendLine("            document.getElementById('pipelineFilter').value = '';")
              .AppendLine("            document.getElementById('phaseFilter').value = '';")
              .AppendLine("            document.getElementById('moduleFilter').value = '';")
              .AppendLine("            document.getElementById('itemFilter').value = '';")
              .AppendLine("            filteredEvents = [...allEvents];")
              .AppendLine("            document.getElementById('filteredCount').textContent = filteredEvents.length;")
              .AppendLine("            generateDiagram();")
              .AppendLine("        }")
              .AppendLine("")
              .AppendLine("        function generateDiagram() {")
              .AppendLine("            if (filteredEvents.length === 0) {")
              .AppendLine("                document.getElementById('mermaidDiagram').innerHTML = '<p style=\"text-align:center; color:#999;\">No events match the current filters</p>';")
              .AppendLine("                return;")
              .AppendLine("            }")
              .AppendLine("")
              .AppendLine("            const groupByItem = document.getElementById('groupByItem').checked;")
              .AppendLine("            ")
              .AppendLine("            if (groupByItem) {")
              .AppendLine("                generateDiagramGroupedByItem();")
              .AppendLine("            } else {")
              .AppendLine("                generateDiagramGroupedByPhase();")
              .AppendLine("            }")
              .AppendLine("        }")
              .AppendLine("")
              .AppendLine("        function generateDiagramGroupedByItem() {")
              .AppendLine("            const orientation = document.getElementById('orientationLR').checked ? 'LR' : 'TD';")
              .AppendLine("            let mermaidCode = `graph ${orientation}\\n`;")
              .AppendLine("            const eventNodeMap = {}; // Map to store event nodes for sub-pipeline linking")
              .AppendLine("            const pipelineFirstNodes = {}; // Track first node of each pipeline")
              .AppendLine("")
              .AppendLine("            // Color palette for pipelines")
              .AppendLine("            const pipelineColors = [")
              .AppendLine("                { border: '#01579b', bg: '#e3f2fd' },  // Blue")
              .AppendLine("                { border: '#6a1b9a', bg: '#f3e5f5' },  // Purple")
              .AppendLine("                { border: '#c62828', bg: '#ffebee' },  // Red")
              .AppendLine("                { border: '#2e7d32', bg: '#e8f5e9' },  // Green")
              .AppendLine("                { border: '#f57c00', bg: '#fff3e0' },  // Orange")
              .AppendLine("                { border: '#0277bd', bg: '#e1f5fe' },  // Cyan")
              .AppendLine("                { border: '#5d4037', bg: '#efebe9' },  // Brown")
              .AppendLine("                { border: '#d32f2f', bg: '#fce4ec' }   // Pink")
              .AppendLine("            ];")
              .AppendLine("")
              .AppendLine("            const eventsByPipeline = {};")
              .AppendLine("            filteredEvents.forEach(e => {")
              .AppendLine("                if (!eventsByPipeline[e.PipelineId]) eventsByPipeline[e.PipelineId] = [];")
              .AppendLine("                eventsByPipeline[e.PipelineId].push(e);")
              .AppendLine("            });")
              .AppendLine("")
              .AppendLine("            // Assign colors to pipelines")
              .AppendLine("            const pipelineColorMap = {};")
              .AppendLine("            Object.keys(eventsByPipeline).forEach((pipelineId, idx) => {")
              .AppendLine("                pipelineColorMap[pipelineId] = pipelineColors[idx % pipelineColors.length];")
              .AppendLine("            });")
              .AppendLine("")
              .AppendLine("            for (const [pipelineId, events] of Object.entries(eventsByPipeline)) {")
              .AppendLine("                const safePipelineId = sanitizeId(pipelineId);")
              .AppendLine("                const pipelineColor = pipelineColorMap[pipelineId];")
              .AppendLine("                let previousEventId = null; // Moved outside item loop to maintain continuity")
              .AppendLine("")
              .AppendLine("                // Group by ItemId first")
              .AppendLine("                const eventsByItem = {};")
              .AppendLine("                events.forEach(e => {")
              .AppendLine("                    const itemKey = e.ItemId || '(global)';")
              .AppendLine("                    if (!eventsByItem[itemKey]) eventsByItem[itemKey] = [];")
              .AppendLine("                    eventsByItem[itemKey].push(e);")
              .AppendLine("                });")
              .AppendLine("")
              .AppendLine("                for (const [itemId, itemEvents] of Object.entries(eventsByItem)) {")
              .AppendLine("                    const safeItemId = sanitizeId(itemId);")
              .AppendLine("                    const itemLabel = itemId === '(global)' ? 'Global' : itemId;")
              .AppendLine("                    mermaidCode += `        subgraph ${safePipelineId}_${safeItemId}[\\\"${itemLabel}\\\"]\\n`;")
              .AppendLine("")
              .AppendLine("                    // Group by Phase within each Item")
              .AppendLine("                    const eventsByPhase = {};")
              .AppendLine("                    itemEvents.forEach(e => {")
              .AppendLine("                        if (!eventsByPhase[e.PhaseId]) eventsByPhase[e.PhaseId] = [];")
              .AppendLine("                        eventsByPhase[e.PhaseId].push(e);")
              .AppendLine("                    });")
              .AppendLine("")
              .AppendLine("                    for (const [phaseId, phaseEvents] of Object.entries(eventsByPhase)) {")
              .AppendLine("                        const safePhaseId = sanitizeId(phaseId);")
              .AppendLine("                        const showPipelineIdInLabel = document.getElementById('showPipelineId')?.checked || false;")
              .AppendLine("")
              .AppendLine("                        // Pair Started and Completed events")
              .AppendLine("                        const pairedEvents = [];")
              .AppendLine("                        const orphans = [];")
              .AppendLine("                        ")
              .AppendLine("                        for (let i = 0; i < phaseEvents.length; i++) {")
              .AppendLine("                            const evt = phaseEvents[i];")
              .AppendLine("                            ")
              .AppendLine("                            if (evt.Name === 'PhaseStarted') {")
              .AppendLine("                                // Look for matching Completed or Failed")
              .AppendLine("                                const matchIdx = phaseEvents.findIndex((e, idx) => ")
              .AppendLine("                                    idx > i && ")
              .AppendLine("                                    (e.Name === 'PhaseCompleted' || e.Name === 'PhaseFailed') &&")
              .AppendLine("                                    e.PhaseId === evt.PhaseId &&")
              .AppendLine("                                    e.ModuleId === evt.ModuleId")
              .AppendLine("                                );")
              .AppendLine("                                ")
              .AppendLine("                                if (matchIdx !== -1) {")
              .AppendLine("                                    pairedEvents.push({ start: evt, end: phaseEvents[matchIdx] });")
              .AppendLine("                                    phaseEvents.splice(matchIdx, 1); // Remove matched event")
              .AppendLine("                                } else {")
              .AppendLine("                                    orphans.push(evt);")
              .AppendLine("                                }")
              .AppendLine("                            } else {")
              .AppendLine("                                // Orphan Completed or Failed without Start")
              .AppendLine("                                orphans.push(evt);")
              .AppendLine("                            }")
              .AppendLine("                        }")
              .AppendLine("")
              .AppendLine("                        // Generate nodes for paired events")
              .AppendLine("                        pairedEvents.forEach((pair, idx) => {")
              .AppendLine("                            const eventId = `${safePipelineId}_${safeItemId}_${safePhaseId}_pair${idx}`;")
              .AppendLine("                            const moduleInfo = pair.start.ModuleId ? `Module: ${pair.start.ModuleId}<br/>` : '';")
              .AppendLine("                            const pipelineInfo = (showPipelineIdInLabel && pair.start.PipelineId !== pipelineId) ? `[${pair.start.PipelineId}]<br/>` : '';")
              .AppendLine("                            ")
              .AppendLine("                            const startTime = new Date(pair.start.Timestamp).toLocaleTimeString();")
              .AppendLine("                            let status = '';")
              .AppendLine("                            let durationInfo = '';")
              .AppendLine("")
              .AppendLine("                            if (pair.end.Name === 'PhaseCompleted') {")
              .AppendLine("                                status = '✓';")
              .AppendLine("                                durationInfo = `${pair.end.Duration.toFixed(0)}ms`;")
              .AppendLine("                            } else if (pair.end.Name === 'PhaseFailed') {")
              .AppendLine("                                status = '✗';")
              .AppendLine("                                const error = pair.end.Error.length > 30 ? pair.end.Error.substring(0, 30) + '...' : pair.end.Error;")
              .AppendLine("                                durationInfo = error;")
              .AppendLine("                            }")
              .AppendLine("")
              .AppendLine("                            const label = `${pipelineInfo}${pair.start.PhaseId} ${status}<br/>${moduleInfo}${startTime} | ${durationInfo}`;")
              .AppendLine("                            mermaidCode += `            ${eventId}[\\\"${label}\\\"]\\n`;")
              .AppendLine("                            ")
              .AppendLine("                            // Use pipeline color with opacity based on status")
              .AppendLine("                            const style = pair.end.Name === 'PhaseFailed' ? ")
              .AppendLine("                                `fill:#ffcdd2,stroke:#c62828,stroke-width:3px` :")
              .AppendLine("                                `fill:${pipelineColor.bg},stroke:${pipelineColor.border},stroke-width:2px`;")
              .AppendLine("                            mermaidCode += `            style ${eventId} ${style}\\n`;")
              .AppendLine("")
              .AppendLine("                            if (previousEventId) {")
              .AppendLine("                                mermaidCode += `            ${previousEventId} --> ${eventId}\\n`;")
              .AppendLine("                            } else if (!pipelineFirstNodes[pipelineId]) {")
              .AppendLine("                                // Store first node of this pipeline")
              .AppendLine("                                pipelineFirstNodes[pipelineId] = eventId;")
              .AppendLine("                            }")
              .AppendLine("")
              .AppendLine("                            // Store node for sub-pipeline linking")
              .AppendLine("                            const key = `${pair.start.PipelineId}_${pair.start.PhaseId}_${pair.start.ModuleId}_${pair.start.ItemId}`;")
              .AppendLine("                            eventNodeMap[key] = eventId;")
              .AppendLine("")
              .AppendLine("                            previousEventId = eventId;")
              .AppendLine("                        });")
              .AppendLine("")
              .AppendLine("                        // Generate nodes for orphan events")
              .AppendLine("                        orphans.forEach((evt, idx) => {")
              .AppendLine("                            const eventId = `${safePipelineId}_${safeItemId}_${safePhaseId}_orphan${idx}`;")
              .AppendLine("                            const moduleInfo = evt.ModuleId ? `Module: ${evt.ModuleId}<br/>` : '';")
              .AppendLine("                            const pipelineInfo = (showPipelineIdInLabel && evt.PipelineId !== pipelineId) ? `[${evt.PipelineId}]<br/>` : '';")
              .AppendLine("")
              .AppendLine("                            let label = '';")
              .AppendLine("                            let style = '';")
              .AppendLine("")
              .AppendLine("                            if (evt.Name === 'PhaseStarted') {")
              .AppendLine("                                const time = new Date(evt.Timestamp).toLocaleTimeString();")
              .AppendLine("                                label = `${pipelineInfo}${evt.PhaseId} Started<br/>${moduleInfo}${time}`;")
              .AppendLine("                                style = `fill:${pipelineColor.bg},stroke:${pipelineColor.border},stroke-width:2px,stroke-dasharray: 5 5`;")
              .AppendLine("                            } else if (evt.Name === 'PhaseCompleted') {")
              .AppendLine("                                label = `${pipelineInfo}${evt.PhaseId} Completed<br/>${moduleInfo}${evt.Duration.toFixed(0)}ms`;")
              .AppendLine("                                style = `fill:${pipelineColor.bg},stroke:${pipelineColor.border},stroke-width:2px`;")
              .AppendLine("                            } else if (evt.Name === 'PhaseFailed') {")
              .AppendLine("                                const error = evt.Error.length > 30 ? evt.Error.substring(0, 30) + '...' : evt.Error;")
              .AppendLine("                                label = `${pipelineInfo}${evt.PhaseId} Failed<br/>${moduleInfo}${error}`;")
              .AppendLine("                                style = 'fill:#ffcdd2,stroke:#c62828,stroke-width:3px';")
              .AppendLine("                            }")
              .AppendLine("")
              .AppendLine("                            mermaidCode += `            ${eventId}[\\\"${label}\\\"]\\n`;")
              .AppendLine("                            mermaidCode += `            style ${eventId} ${style}\\n`;")
              .AppendLine("")
              .AppendLine("                            if (previousEventId) {")
              .AppendLine("                                mermaidCode += `            ${previousEventId} --> ${eventId}\\n`;")
              .AppendLine("                            } else if (!pipelineFirstNodes[pipelineId]) {")
              .AppendLine("                                // Store first node of this pipeline")
              .AppendLine("                                pipelineFirstNodes[pipelineId] = eventId;")
              .AppendLine("                            }")
              .AppendLine("")
              .AppendLine("                            previousEventId = eventId;")
              .AppendLine("                        });")
              .AppendLine("                    }")
              .AppendLine("")
              .AppendLine("                    mermaidCode += '        end\\n';")
              .AppendLine("                }")
              .AppendLine("            }")
              .AppendLine("")
              .AppendLine("            addPipelineLinksAndRender(mermaidCode, eventNodeMap, pipelineFirstNodes);")
              .AppendLine("        }")
              .AppendLine("")
              .AppendLine("        function generateDiagramGroupedByPhase() {")
              .AppendLine("            const orientation = document.getElementById('orientationLR').checked ? 'LR' : 'TD';")
              .AppendLine("            let mermaidCode = `graph ${orientation}\\n`;")
              .AppendLine("")
              .AppendLine("            // Color palette for pipelines")
              .AppendLine("            const pipelineColors = [")
              .AppendLine("                { border: '#01579b', bg: '#e3f2fd' },  // Blue")
              .AppendLine("                { border: '#6a1b9a', bg: '#f3e5f5' },  // Purple")
              .AppendLine("                { border: '#c62828', bg: '#ffebee' },  // Red")
              .AppendLine("                { border: '#2e7d32', bg: '#e8f5e9' },  // Green")
              .AppendLine("                { border: '#f57c00', bg: '#fff3e0' },  // Orange")
              .AppendLine("                { border: '#0277bd', bg: '#e1f5fe' },  // Cyan")
              .AppendLine("                { border: '#5d4037', bg: '#efebe9' },  // Brown")
              .AppendLine("                { border: '#d32f2f', bg: '#fce4ec' }   // Pink")
              .AppendLine("            ];")
              .AppendLine("")
              .AppendLine("            const eventsByPipeline = {};")
              .AppendLine("            filteredEvents.forEach(e => {")
              .AppendLine("                if (!eventsByPipeline[e.PipelineId]) eventsByPipeline[e.PipelineId] = [];")
              .AppendLine("                eventsByPipeline[e.PipelineId].push(e);")
              .AppendLine("            });")
              .AppendLine("")
              .AppendLine("            // Assign colors to pipelines")
              .AppendLine("            const pipelineColorMap = {};")
              .AppendLine("            Object.keys(eventsByPipeline).forEach((pipelineId, idx) => {")
              .AppendLine("                pipelineColorMap[pipelineId] = pipelineColors[idx % pipelineColors.length];")
              .AppendLine("            });")
              .AppendLine("")
              .AppendLine("            for (const [pipelineId, events] of Object.entries(eventsByPipeline)) {")
              .AppendLine("                const safePipelineId = sanitizeId(pipelineId);")
              .AppendLine("                const pipelineColor = pipelineColorMap[pipelineId];")
              .AppendLine("")
              .AppendLine("                const eventsByPhase = {};")
              .AppendLine("                events.forEach(e => {")
              .AppendLine("                    if (!eventsByPhase[e.PhaseId]) eventsByPhase[e.PhaseId] = [];")
              .AppendLine("                    eventsByPhase[e.PhaseId].push(e);")
              .AppendLine("                });")
              .AppendLine("")
              .AppendLine("                let previousEventId = null;")
              .AppendLine("")
              .AppendLine("                for (const [phaseId, phaseEvents] of Object.entries(eventsByPhase)) {")
              .AppendLine("                    const safePhaseId = sanitizeId(phaseId);")
              .AppendLine("                    mermaidCode += `        subgraph ${safePipelineId}_${safePhaseId}[\\\"${phaseId}\\\"]\\n`;")
              .AppendLine("")
              .AppendLine("                    let previousPhaseEventId = null;")
              .AppendLine("")
              .AppendLine("                    phaseEvents.forEach((evt, idx) => {")
              .AppendLine("                        const eventId = `${safePipelineId}_${safePhaseId}_evt${idx}`;")
              .AppendLine("                        const itemInfo = evt.ItemId ? `<br/>Item: ${evt.ItemId}` : '';")
              .AppendLine("                        const moduleInfo = evt.ModuleId ? `<br/>Module: ${evt.ModuleId}` : '';")
              .AppendLine("")
              .AppendLine("                        let label = '';")
              .AppendLine("                        let style = '';")
              .AppendLine("")
              .AppendLine("                        if (evt.Name === 'PhaseStarted') {")
              .AppendLine("                            const time = new Date(evt.Timestamp).toLocaleTimeString();")
              .AppendLine("                            label = `Started${moduleInfo}${itemInfo}<br/>${time}`;")
              .AppendLine("                            style = `fill:${pipelineColor.bg},stroke:${pipelineColor.border},stroke-width:2px,stroke-dasharray: 5 5`;")
              .AppendLine("                        } else if (evt.Name === 'PhaseCompleted') {")
              .AppendLine("                            label = `Completed${moduleInfo}${itemInfo}<br/>${evt.Duration.toFixed(0)}ms`;")
              .AppendLine("                            style = `fill:${pipelineColor.bg},stroke:${pipelineColor.border},stroke-width:2px`;")
              .AppendLine("                        } else if (evt.Name === 'PhaseFailed') {")
              .AppendLine("                            const error = evt.Error.length > 50 ? evt.Error.substring(0, 50) + '...' : evt.Error;")
              .AppendLine("                            label = `Failed${moduleInfo}${itemInfo}<br/>${error}`;")
              .AppendLine("                            style = 'fill:#ffcdd2,stroke:#c62828,stroke-width:3px';")
              .AppendLine("                        }")
              .AppendLine("")
              .AppendLine("                        mermaidCode += `            ${eventId}[\\\"${label}\\\"]\\n`;")
              .AppendLine("                        mermaidCode += `            style ${eventId} ${style}\\n`;")
              .AppendLine("")
              .AppendLine("                        if (previousPhaseEventId) {")
              .AppendLine("                            mermaidCode += `            ${previousPhaseEventId} --> ${eventId}\\n`;")
              .AppendLine("                        }")
              .AppendLine("")
              .AppendLine("                        previousPhaseEventId = eventId;")
              .AppendLine("                    });")
              .AppendLine("")
              .AppendLine("                    mermaidCode += '        end\\n';")
              .AppendLine("")
              .AppendLine("                    if (previousEventId) {")
              .AppendLine("                        mermaidCode += `        ${previousEventId} -.-> ${previousPhaseEventId}\\n`;")
              .AppendLine("                    }")
              .AppendLine("                    previousEventId = previousPhaseEventId;")
              .AppendLine("                }")
              .AppendLine("            }")
              .AppendLine("")
              .AppendLine("            addPipelineLinksAndRender(mermaidCode, {}, {});")
              .AppendLine("        }")
              .AppendLine("")
              .AppendLine("        function addPipelineLinksAndRender(mermaidCode, eventNodeMap = {}, pipelineFirstNodes = {}) {")
              .AppendLine("            // Add pipeline hierarchy links if enabled")
              .AppendLine("            const showPipelineLinks = document.getElementById('showPipelineLinks').checked;")
              .AppendLine("            if (showPipelineLinks) {")
              .AppendLine("                // Build parent-child relationships")
              .AppendLine("                const subPipelines = {};")
              .AppendLine("                filteredEvents.forEach(e => {")
              .AppendLine("                    if (e.ParentPipelineId && !subPipelines[e.PipelineId]) {")
              .AppendLine("                        subPipelines[e.PipelineId] = {")
              .AppendLine("                            parentPipelineId: e.ParentPipelineId,")
              .AppendLine("                            firstEvent: e")
              .AppendLine("                        };")
              .AppendLine("                    }")
              .AppendLine("                });")
              .AppendLine("")
              .AppendLine("                // Create links from parent event to child pipeline")
              .AppendLine("                for (const [childPipelineId, info] of Object.entries(subPipelines)) {")
              .AppendLine("                    const safeChildId = sanitizeId(childPipelineId);")
              .AppendLine("                    const firstChildEvent = info.firstEvent;")
              .AppendLine("                    const childItemKey = firstChildEvent.ItemId || '(global)';")
              .AppendLine("                    const childPipelineCurrentPhaseKey = firstChildEvent.PipelineCurrentPhaseKey;")
              .AppendLine("")
              .AppendLine("                    // Find the parent event that launched this sub-pipeline")
              .AppendLine("                    // The parent event's PhaseId should match the child's PipelineCurrentPhaseKey")
              .AppendLine("                    let parentEvents = filteredEvents")
              .AppendLine("                        .filter(e => ")
              .AppendLine("                            e.PipelineId === info.parentPipelineId &&")
              .AppendLine("                            e.PhaseId === childPipelineCurrentPhaseKey && // Match PhaseId with child's CurrentPhaseKey")
              .AppendLine("                            new Date(e.Timestamp) < new Date(firstChildEvent.Timestamp)")
              .AppendLine("                        )")
              .AppendLine("                        .sort((a, b) => new Date(b.Timestamp) - new Date(a.Timestamp));")
              .AppendLine("                    ")
              .AppendLine("                    // If no exact match found, fallback to last event before child starts")
              .AppendLine("                    if (parentEvents.length === 0) {")
              .AppendLine("                        parentEvents = filteredEvents")
              .AppendLine("                            .filter(e => ")
              .AppendLine("                                e.PipelineId === info.parentPipelineId &&")
              .AppendLine("                                (e.ItemId || '(global)') === childItemKey &&")
              .AppendLine("                                new Date(e.Timestamp) < new Date(firstChildEvent.Timestamp)")
              .AppendLine("                            )")
              .AppendLine("                            .sort((a, b) => new Date(b.Timestamp) - new Date(a.Timestamp));")
              .AppendLine("                        ")
              .AppendLine("                        // If still no match with same ItemId, try global events")
              .AppendLine("                        if (parentEvents.length === 0 && childItemKey !== '(global)') {")
              .AppendLine("                            parentEvents = filteredEvents")
              .AppendLine("                                .filter(e => ")
              .AppendLine("                                    e.PipelineId === info.parentPipelineId &&")
              .AppendLine("                                    !e.ItemId && // Global event (no ItemId)")
              .AppendLine("                                    new Date(e.Timestamp) < new Date(firstChildEvent.Timestamp)")
              .AppendLine("                                )")
              .AppendLine("                                .sort((a, b) => new Date(b.Timestamp) - new Date(a.Timestamp));")
              .AppendLine("                        }")
              .AppendLine("                    }")
              .AppendLine("")
              .AppendLine("                    let parentEventNode = null;")
              .AppendLine("                    ")
              .AppendLine("                    // Try to find the parent node in eventNodeMap")
              .AppendLine("                    for (const parentEvent of parentEvents) {")
              .AppendLine("                        const parentKey = `${parentEvent.PipelineId}_${parentEvent.PhaseId}_${parentEvent.ModuleId}_${parentEvent.ItemId}`;")
              .AppendLine("                        if (eventNodeMap[parentKey]) {")
              .AppendLine("                            parentEventNode = eventNodeMap[parentKey];")
              .AppendLine("                            break;")
              .AppendLine("                        }")
              .AppendLine("                    }")
              .AppendLine("")
              .AppendLine("                    if (parentEventNode) {")
              .AppendLine("                        // Use the stored first node ID of the child pipeline")
              .AppendLine("                        const firstChildNodeId = pipelineFirstNodes[childPipelineId];")
              .AppendLine("                        if (firstChildNodeId) {")
              .AppendLine("                            mermaidCode += `    ${parentEventNode} ==>|sub-pipeline| ${firstChildNodeId}\\n`;")
              .AppendLine("                        }")
              .AppendLine("                    }")
              .AppendLine("                    // Note: If parent node not found, skip the link to avoid invalid Mermaid syntax")
              .AppendLine("                }")
              .AppendLine("            }")
              .AppendLine("")
              .AppendLine("            const container = document.getElementById('mermaidDiagram');")
              .AppendLine("            container.innerHTML = mermaidCode;")
              .AppendLine("            container.removeAttribute('data-processed');")
              .AppendLine("            window.mermaid.run({ nodes: [container] });")
              .AppendLine("        }")
              .AppendLine("")
              .AppendLine("        // Re-generate diagram when checkboxes change")
              .AppendLine("        document.getElementById('showPipelineLinks')?.addEventListener('change', () => {")
              .AppendLine("            generateDiagram();")
              .AppendLine("        });")
              .AppendLine("")
              .AppendLine("        document.getElementById('groupByItem')?.addEventListener('change', () => {")
              .AppendLine("            generateDiagram();")
              .AppendLine("        });")
              .AppendLine("")
              .AppendLine("        document.getElementById('showPipelineId')?.addEventListener('change', () => {")
              .AppendLine("            generateDiagram();")
              .AppendLine("        });")
              .AppendLine("")
              .AppendLine("        document.getElementById('orientationLR')?.addEventListener('change', () => {")
              .AppendLine("            generateDiagram();")
              .AppendLine("        });")
              .AppendLine("")
              .AppendLine("        document.getElementById('orientationTD')?.addEventListener('change', () => {")
              .AppendLine("            generateDiagram();")
              .AppendLine("        });")
              .AppendLine("")
              .AppendLine("        // Zoom functionality")
              .AppendLine("        let currentZoom = 1.0;")
              .AppendLine("        const minZoom = 0.1;")
              .AppendLine("        const maxZoom = 5.0;")
              .AppendLine("        const zoomStep = 0.1;")
              .AppendLine("")
              .AppendLine("        function updateZoom(newZoom) {")
              .AppendLine("            currentZoom = Math.max(minZoom, Math.min(maxZoom, newZoom));")
              .AppendLine("            const diagram = document.getElementById('mermaidDiagram');")
              .AppendLine("            diagram.style.transform = `scale(${currentZoom})`;")
              .AppendLine("            document.getElementById('zoomLevel').textContent = `${Math.round(currentZoom * 100)}%`;")
              .AppendLine("            ")
              .AppendLine("            // Disable/enable buttons based on zoom level")
              .AppendLine("            document.getElementById('zoomOut').disabled = currentZoom <= minZoom;")
              .AppendLine("            document.getElementById('zoomIn').disabled = currentZoom >= maxZoom;")
              .AppendLine("        }")
              .AppendLine("")
              .AppendLine("        document.getElementById('zoomIn')?.addEventListener('click', () => {")
              .AppendLine("            updateZoom(currentZoom + zoomStep);")
              .AppendLine("        });")
              .AppendLine("")
              .AppendLine("        document.getElementById('zoomOut')?.addEventListener('click', () => {")
              .AppendLine("            updateZoom(currentZoom - zoomStep);")
              .AppendLine("        });")
              .AppendLine("")
              .AppendLine("        document.getElementById('zoomReset')?.addEventListener('click', () => {")
              .AppendLine("            updateZoom(1.0);")
              .AppendLine("        });")
              .AppendLine("")
              .AppendLine("        // Mouse wheel zoom (with Ctrl key)")
              .AppendLine("        document.getElementById('mermaidContainer')?.addEventListener('wheel', (e) => {")
              .AppendLine("            if (e.ctrlKey) {")
              .AppendLine("                e.preventDefault();")
              .AppendLine("                const delta = e.deltaY > 0 ? -zoomStep : zoomStep;")
              .AppendLine("                updateZoom(currentZoom + delta);")
              .AppendLine("            }")
              .AppendLine("        }, { passive: false });")
              .AppendLine("")
              .AppendLine("        // Initialize on page load")
              .AppendLine("        document.addEventListener('DOMContentLoaded', () => {")
              .AppendLine("            populateFilters();")
              .AppendLine("            applyFilters();")
              .AppendLine("        });")
              .AppendLine("    </script>")
              .AppendLine("</body>")
              .AppendLine("</html>");

        return sb.ToString();
    }
}
