using System.Globalization;
using System.Text;
using System.Text.Json;

using ContextCompiler.Abstractions.Pipelines;
using ContextCompiler.Abstractions.Pipelines.Events;

namespace ContextCompiler.Reports.Modules.Pipelines.Mermaid;

internal static class InteractiveMermaidHtmlGenerator
{
    public static string GenerateHtml(IReadOnlyList<IPipelineEvent> events, string title = "Pipeline Execution Report - Interactive")
    {
        StringBuilder sb = new();

        // Serialize events to JSON for JavaScript
        string eventsJson = JsonSerializer.Serialize(events.Select(e =>
        {
            string? parentPipelineId = null;
            if (e.RunContext is ISubPipelineRunContext subContext)
            {
                parentPipelineId = subContext.Parent.Pipeline.Id;
            }

            return new
            {
                e.Name,
                PipelineId = e.RunContext.Pipeline.Id,
                ParentPipelineId = parentPipelineId,
                e.PhaseId,
                e.ModuleId,
                e.ItemId,
                Timestamp = e.Timestamp.ToString("o"),
                Duration = e is PhaseCompleted completed ? completed.Duration.TotalMilliseconds : (double?)null,
                Error = e is PhaseFailed failed ? failed.Exception.Message : null
            };
        }));

        _ = sb.AppendLine("<!DOCTYPE html>")
              .AppendLine("<html lang=\"en\">")
              .AppendLine("<head>")
              .AppendLine("    <meta charset=\"UTF-8\">")
              .AppendLine("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">")
              .AppendLine(CultureInfo.InvariantCulture, $"    <title>{title}</title>")
              .AppendLine("    <script type=\"module\">")
              .AppendLine("        import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';")
              .AppendLine("        window.mermaid = mermaid;")
              .AppendLine("        mermaid.initialize({ ")
              .AppendLine("            startOnLoad: false,")
              .AppendLine("            theme: 'default',")
              .AppendLine("            maxTextSize: 200000,")
              .AppendLine("            maxEdges: 2000,")
              .AppendLine("            flowchart: {")
              .AppendLine("                useMaxWidth: true,")
              .AppendLine("                htmlLabels: true,")
              .AppendLine("                curve: 'basis'")
              .AppendLine("            }")
              .AppendLine("        });")
              .AppendLine("    </script>")
              .AppendLine("    <style>")
              .AppendLine("        body {")
              .AppendLine("            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;")
              .AppendLine("            margin: 0;")
              .AppendLine("            padding: 20px;")
              .AppendLine("            background: #f5f5f5;")
              .AppendLine("        }")
              .AppendLine("        .container {")
              .AppendLine("            max-width: 1600px;")
              .AppendLine("            margin: 0 auto;")
              .AppendLine("            background: white;")
              .AppendLine("            padding: 30px;")
              .AppendLine("            border-radius: 8px;")
              .AppendLine("            box-shadow: 0 2px 4px rgba(0,0,0,0.1);")
              .AppendLine("        }")
              .AppendLine("        h1 {")
              .AppendLine("            color: #333;")
              .AppendLine("            margin-top: 0;")
              .AppendLine("            border-bottom: 3px solid #01579b;")
              .AppendLine("            padding-bottom: 10px;")
              .AppendLine("        }")
              .AppendLine("        .filters {")
              .AppendLine("            background: #f9f9f9;")
              .AppendLine("            border: 1px solid #ddd;")
              .AppendLine("            border-radius: 4px;")
              .AppendLine("            padding: 20px;")
              .AppendLine("            margin-bottom: 20px;")
              .AppendLine("        }")
              .AppendLine("        .filters h3 {")
              .AppendLine("            margin-top: 0;")
              .AppendLine("            color: #555;")
              .AppendLine("        }")
              .AppendLine("        .filter-group {")
              .AppendLine("            display: inline-block;")
              .AppendLine("            margin-right: 20px;")
              .AppendLine("            margin-bottom: 10px;")
              .AppendLine("        }")
              .AppendLine("        .filter-group label {")
              .AppendLine("            display: block;")
              .AppendLine("            font-weight: 600;")
              .AppendLine("            margin-bottom: 5px;")
              .AppendLine("            color: #555;")
              .AppendLine("        }")
              .AppendLine("        .filter-group select {")
              .AppendLine("            padding: 8px 12px;")
              .AppendLine("            border: 1px solid #ccc;")
              .AppendLine("            border-radius: 4px;")
              .AppendLine("            background: white;")
              .AppendLine("            font-size: 14px;")
              .AppendLine("            min-width: 200px;")
              .AppendLine("        }")
              .AppendLine("        .filter-actions {")
              .AppendLine("            margin-top: 15px;")
              .AppendLine("        }")
              .AppendLine("        .filter-actions button {")
              .AppendLine("            padding: 10px 20px;")
              .AppendLine("            margin-right: 10px;")
              .AppendLine("            border: none;")
              .AppendLine("            border-radius: 4px;")
              .AppendLine("            font-size: 14px;")
              .AppendLine("            cursor: pointer;")
              .AppendLine("            font-weight: 600;")
              .AppendLine("        }")
              .AppendLine("        .btn-apply {")
              .AppendLine("            background: #01579b;")
              .AppendLine("            color: white;")
              .AppendLine("        }")
              .AppendLine("        .btn-apply:hover {")
              .AppendLine("            background: #014078;")
              .AppendLine("        }")
              .AppendLine("        .btn-reset {")
              .AppendLine("            background: #757575;")
              .AppendLine("            color: white;")
              .AppendLine("        }")
              .AppendLine("        .btn-reset:hover {")
              .AppendLine("            background: #616161;")
              .AppendLine("        }")
              .AppendLine("        .info-box {")
              .AppendLine("            background: #e3f2fd;")
              .AppendLine("            border: 1px solid #01579b;")
              .AppendLine("            border-radius: 4px;")
              .AppendLine("            padding: 15px;")
              .AppendLine("            margin-bottom: 20px;")
              .AppendLine("        }")
              .AppendLine("        .info-box p {")
              .AppendLine("            margin: 5px 0;")
              .AppendLine("            color: #01579b;")
              .AppendLine("        }")
              .AppendLine("        .mermaid-container {")
              .AppendLine("            margin: 20px 0;")
              .AppendLine("            overflow-x: auto;")
              .AppendLine("            border: 1px solid #ddd;")
              .AppendLine("            border-radius: 4px;")
              .AppendLine("            padding: 20px;")
              .AppendLine("            background: white;")
              .AppendLine("        }")
              .AppendLine("        #mermaidDiagram {")
              .AppendLine("            text-align: center;")
              .AppendLine("        }")
              .AppendLine("        .legend {")
              .AppendLine("            margin-top: 30px;")
              .AppendLine("            padding: 15px;")
              .AppendLine("            background: #f9f9f9;")
              .AppendLine("            border-radius: 4px;")
              .AppendLine("        }")
              .AppendLine("        .legend h3 {")
              .AppendLine("            margin-top: 0;")
              .AppendLine("            color: #555;")
              .AppendLine("        }")
              .AppendLine("        .legend-item {")
              .AppendLine("            display: inline-block;")
              .AppendLine("            margin-right: 20px;")
              .AppendLine("            margin-bottom: 10px;")
              .AppendLine("        }")
              .AppendLine("        .legend-box {")
              .AppendLine("            display: inline-block;")
              .AppendLine("            width: 20px;")
              .AppendLine("            height: 20px;")
              .AppendLine("            margin-right: 8px;")
              .AppendLine("            vertical-align: middle;")
              .AppendLine("            border-radius: 3px;")
              .AppendLine("        }")
              .AppendLine("        .started { background: #e1f5fe; border: 2px solid #01579b; }")
              .AppendLine("        .completed { background: #c8e6c9; border: 2px solid #2e7d32; }")
              .AppendLine("        .failed { background: #ffcdd2; border: 2px solid #c62828; }")
              .AppendLine("        .timestamp {")
              .AppendLine("            color: #666;")
              .AppendLine("            font-size: 0.9em;")
              .AppendLine("            margin-top: 20px;")
              .AppendLine("        }")
              .AppendLine("        .loading {")
              .AppendLine("            text-align: center;")
              .AppendLine("            padding: 40px;")
              .AppendLine("            color: #666;")
              .AppendLine("        }")
              .AppendLine("    </style>")
              .AppendLine("</head>")
              .AppendLine("<body>")
              .AppendLine("    <div class=\"container\">")
              .AppendLine(CultureInfo.InvariantCulture, $"        <h1>{title}</h1>")
              .AppendLine("        <div class=\"filters\">")
              .AppendLine("            <h3>🔍 Filters - Select what to visualize</h3>")
              .AppendLine("            <div class=\"filter-group\">")
              .AppendLine("                <label for=\"pipelineFilter\">Pipeline:</label>")
              .AppendLine("                <select id=\"pipelineFilter\">")
              .AppendLine("                    <option value=\"\">All Pipelines</option>")
              .AppendLine("                </select>")
              .AppendLine("            </div>")
              .AppendLine("            <div class=\"filter-group\">")
              .AppendLine("                <label for=\"phaseFilter\">Phase:</label>")
              .AppendLine("                <select id=\"phaseFilter\">")
              .AppendLine("                    <option value=\"\">All Phases</option>")
              .AppendLine("                </select>")
              .AppendLine("            </div>")
              .AppendLine("            <div class=\"filter-group\">")
              .AppendLine("                <label for=\"moduleFilter\">Module:</label>")
              .AppendLine("                <select id=\"moduleFilter\">")
              .AppendLine("                    <option value=\"\">All Modules</option>")
              .AppendLine("                </select>")
              .AppendLine("            </div>")
              .AppendLine("            <div class=\"filter-group\">")
              .AppendLine("                <label for=\"itemFilter\">Item:</label>")
              .AppendLine("                <select id=\"itemFilter\">")
              .AppendLine("                    <option value=\"\">All Items</option>")
              .AppendLine("                </select>")
              .AppendLine("            </div>")
              .AppendLine("            <div class=\"filter-actions\">")
              .AppendLine("                <button class=\"btn-apply\" onclick=\"applyFilters()\">Apply Filters</button>")
              .AppendLine("                <button class=\"btn-reset\" onclick=\"resetFilters()\">Reset All</button>")
              .AppendLine("            </div>")
              .AppendLine("            <div style=\"margin-top: 15px; padding-top: 15px; border-top: 1px solid #ddd;\">")
              .AppendLine("                <label style=\"display: flex; align-items: center; cursor: pointer; margin-bottom: 10px;\">")
              .AppendLine("                    <input type=\"checkbox\" id=\"showPipelineLinks\" checked style=\"margin-right: 8px;\">")
              .AppendLine("                    <span style=\"font-weight: 600;\">Show pipeline hierarchy links</span>")
              .AppendLine("                </label>")
              .AppendLine("                <label style=\"display: flex; align-items: center; cursor: pointer; margin-bottom: 10px;\">")
              .AppendLine("                    <input type=\"checkbox\" id=\"groupByItem\" checked style=\"margin-right: 8px;\">")
              .AppendLine("                    <span style=\"font-weight: 600;\">Group by Item (shows file journey)</span>")
              .AppendLine("                </label>")
              .AppendLine("                <label style=\"display: flex; align-items: center; cursor: pointer;\">")
              .AppendLine("                    <input type=\"checkbox\" id=\"showPipelineId\" style=\"margin-right: 8px;\">")
              .AppendLine("                    <span style=\"font-weight: 600;\">Show Pipeline ID in labels (helps identify duplicates)</span>")
              .AppendLine("                </label>")
              .AppendLine("            </div>")
              .AppendLine("        </div>")
              .AppendLine("        <div class=\"info-box\" id=\"infoBox\">")
              .AppendLine(CultureInfo.InvariantCulture, $"            <p><strong>Total events:</strong> <span id=\"eventCount\">{events.Count}</span></p>")
              .AppendLine("            <p><strong>Filtered events:</strong> <span id=\"filteredCount\">0</span></p>")
              .AppendLine("        </div>")
              .AppendLine("        <div class=\"mermaid-container\">")
              .AppendLine("            <div id=\"mermaidDiagram\" class=\"loading\">Loading diagram...</div>")
              .AppendLine("        </div>")
              .AppendLine("        <div class=\"legend\">")
              .AppendLine("            <h3>Legend</h3>")
              .AppendLine("            <div class=\"legend-item\">")
              .AppendLine("                <span class=\"legend-box started\"></span>")
              .AppendLine("                <span>Phase Started</span>")
              .AppendLine("            </div>")
              .AppendLine("            <div class=\"legend-item\">")
              .AppendLine("                <span class=\"legend-box completed\"></span>")
              .AppendLine("                <span>Phase Completed</span>")
              .AppendLine("            </div>")
              .AppendLine("            <div class=\"legend-item\">")
              .AppendLine("                <span class=\"legend-box failed\"></span>")
              .AppendLine("                <span>Phase Failed</span>")
              .AppendLine("            </div>")
              .AppendLine("        </div>")
              .AppendLine(CultureInfo.InvariantCulture, $"        <div class=\"timestamp\">Generated: {DateTimeOffset.UtcNow:yyyy-MM-dd HH:mm:ss} UTC</div>")
              .AppendLine("    </div>")
              .AppendLine("    <script>")
              .AppendLine(CultureInfo.InvariantCulture, $"        const allEvents = {eventsJson};")
              .AppendLine("        let filteredEvents = [...allEvents];")
              .AppendLine("")
              .AppendLine("        function sanitizeId(id) {")
              .AppendLine("            return id.replace(/[-\\.\\s\\/\\(\\)\\[\\]\\{\\}<>:;,?!@#$%^&*+=|\\\\`~\"']/g, '_');")
              .AppendLine("        }")
              .AppendLine("")
              .AppendLine("        function populateFilters() {")
              .AppendLine("            const pipelines = [...new Set(allEvents.map(e => e.PipelineId))];")
              .AppendLine("            const phases = [...new Set(allEvents.map(e => e.PhaseId))];")
              .AppendLine("            const modules = [...new Set(allEvents.map(e => e.ModuleId).filter(m => m))];")
              .AppendLine("            const items = [...new Set(allEvents.map(e => e.ItemId).filter(i => i))];")
              .AppendLine("")
              .AppendLine("            const pipelineSelect = document.getElementById('pipelineFilter');")
              .AppendLine("            pipelines.forEach(p => {")
              .AppendLine("                const option = document.createElement('option');")
              .AppendLine("                option.value = p;")
              .AppendLine("                option.textContent = p;")
              .AppendLine("                pipelineSelect.appendChild(option);")
              .AppendLine("            });")
              .AppendLine("")
              .AppendLine("            const phaseSelect = document.getElementById('phaseFilter');")
              .AppendLine("            phases.forEach(p => {")
              .AppendLine("                const option = document.createElement('option');")
              .AppendLine("                option.value = p;")
              .AppendLine("                option.textContent = p;")
              .AppendLine("                phaseSelect.appendChild(option);")
              .AppendLine("            });")
              .AppendLine("")
              .AppendLine("            const moduleSelect = document.getElementById('moduleFilter');")
              .AppendLine("            modules.forEach(m => {")
              .AppendLine("                const option = document.createElement('option');")
              .AppendLine("                option.value = m;")
              .AppendLine("                option.textContent = m;")
              .AppendLine("                moduleSelect.appendChild(option);")
              .AppendLine("            });")
              .AppendLine("")
              .AppendLine("            const itemSelect = document.getElementById('itemFilter');")
              .AppendLine("            items.forEach(i => {")
              .AppendLine("                const option = document.createElement('option');")
              .AppendLine("                option.value = i;")
              .AppendLine("                option.textContent = i;")
              .AppendLine("                itemSelect.appendChild(option);")
              .AppendLine("            });")
              .AppendLine("        }")
              .AppendLine("")
              .AppendLine("        function applyFilters() {")
              .AppendLine("            const pipelineFilter = document.getElementById('pipelineFilter').value;")
              .AppendLine("            const phaseFilter = document.getElementById('phaseFilter').value;")
              .AppendLine("            const moduleFilter = document.getElementById('moduleFilter').value;")
              .AppendLine("            const itemFilter = document.getElementById('itemFilter').value;")
              .AppendLine("")
              .AppendLine("            filteredEvents = allEvents.filter(e => {")
              .AppendLine("                if (pipelineFilter && e.PipelineId !== pipelineFilter) return false;")
              .AppendLine("                if (phaseFilter && e.PhaseId !== phaseFilter) return false;")
              .AppendLine("                if (moduleFilter && e.ModuleId !== moduleFilter) return false;")
              .AppendLine("                if (itemFilter && e.ItemId !== itemFilter) return false;")
              .AppendLine("                return true;")
              .AppendLine("            });")
              .AppendLine("")
              .AppendLine("            document.getElementById('filteredCount').textContent = filteredEvents.length;")
              .AppendLine("            generateDiagram();")
              .AppendLine("        }")
              .AppendLine("")
              .AppendLine("        function resetFilters() {")
              .AppendLine("            document.getElementById('pipelineFilter').value = '';")
              .AppendLine("            document.getElementById('phaseFilter').value = '';")
              .AppendLine("            document.getElementById('moduleFilter').value = '';")
              .AppendLine("            document.getElementById('itemFilter').value = '';")
              .AppendLine("            filteredEvents = [...allEvents];")
              .AppendLine("            document.getElementById('filteredCount').textContent = filteredEvents.length;")
              .AppendLine("            generateDiagram();")
              .AppendLine("        }")
              .AppendLine("")
              .AppendLine("        function generateDiagram() {")
              .AppendLine("            if (filteredEvents.length === 0) {")
              .AppendLine("                document.getElementById('mermaidDiagram').innerHTML = '<p style=\"text-align:center; color:#999;\">No events match the current filters</p>';")
              .AppendLine("                return;")
              .AppendLine("            }")
              .AppendLine("")
              .AppendLine("            const groupByItem = document.getElementById('groupByItem').checked;")
              .AppendLine("            ")
              .AppendLine("            if (groupByItem) {")
              .AppendLine("                generateDiagramGroupedByItem();")
              .AppendLine("            } else {")
              .AppendLine("                generateDiagramGroupedByPhase();")
              .AppendLine("            }")
              .AppendLine("        }")
              .AppendLine("")
              .AppendLine("        function generateDiagramGroupedByItem() {")
              .AppendLine("            let mermaidCode = 'graph TD\\n';")
              .AppendLine("")
              .AppendLine("            const eventsByPipeline = {};")
              .AppendLine("            filteredEvents.forEach(e => {")
              .AppendLine("                if (!eventsByPipeline[e.PipelineId]) eventsByPipeline[e.PipelineId] = [];")
              .AppendLine("                eventsByPipeline[e.PipelineId].push(e);")
              .AppendLine("            });")
              .AppendLine("")
              .AppendLine("            for (const [pipelineId, events] of Object.entries(eventsByPipeline)) {")
              .AppendLine("                const safePipelineId = sanitizeId(pipelineId);")
              .AppendLine("                mermaidCode += `    subgraph ${safePipelineId}[\\\"${pipelineId}\\\"]\\n`;")
              .AppendLine("")
              .AppendLine("                // Group by ItemId first")
              .AppendLine("                const eventsByItem = {};")
              .AppendLine("                events.forEach(e => {")
              .AppendLine("                    const itemKey = e.ItemId || '(global)';")
              .AppendLine("                    if (!eventsByItem[itemKey]) eventsByItem[itemKey] = [];")
              .AppendLine("                    eventsByItem[itemKey].push(e);")
              .AppendLine("                });")
              .AppendLine("")
              .AppendLine("                for (const [itemId, itemEvents] of Object.entries(eventsByItem)) {")
              .AppendLine("                    const safeItemId = sanitizeId(itemId);")
              .AppendLine("                    const itemLabel = itemId === '(global)' ? 'Global' : itemId;")
              .AppendLine("                    mermaidCode += `        subgraph ${safePipelineId}_${safeItemId}[\\\"${itemLabel}\\\"]\\n`;")
              .AppendLine("")
              .AppendLine("                    // Group by Phase within each Item")
              .AppendLine("                    const eventsByPhase = {};")
              .AppendLine("                    itemEvents.forEach(e => {")
              .AppendLine("                        if (!eventsByPhase[e.PhaseId]) eventsByPhase[e.PhaseId] = [];")
              .AppendLine("                        eventsByPhase[e.PhaseId].push(e);")
              .AppendLine("                    });")
              .AppendLine("")
              .AppendLine("                    let previousEventId = null;")
              .AppendLine("")
              .AppendLine("                    for (const [phaseId, phaseEvents] of Object.entries(eventsByPhase)) {")
              .AppendLine("                        const safePhaseId = sanitizeId(phaseId);")
              .AppendLine("")
              .AppendLine("                        phaseEvents.forEach((evt, idx) => {")
              .AppendLine("                            const showPipelineIdInLabel = document.getElementById('showPipelineId')?.checked || false;")
              .AppendLine("                            const eventId = `${safePipelineId}_${safeItemId}_${safePhaseId}_evt${idx}_${sanitizeId(evt.Timestamp)}`;")
              .AppendLine("                            const moduleInfo = evt.ModuleId ? `Module: ${evt.ModuleId}<br/>` : '';")
              .AppendLine("                            const pipelineInfo = (showPipelineIdInLabel && evt.PipelineId !== pipelineId) ? `[${evt.PipelineId}]<br/>` : '';")
              .AppendLine("")
              .AppendLine("                            let label = '';")
              .AppendLine("                            let style = '';")
              .AppendLine("")
              .AppendLine("                            if (evt.Name === 'PhaseStarted') {")
              .AppendLine("                                const time = new Date(evt.Timestamp).toLocaleTimeString();")
              .AppendLine("                                label = `${pipelineInfo}${evt.PhaseId} Started<br/>${moduleInfo}${time}`;")
              .AppendLine("                                style = 'fill:#e1f5fe,stroke:#01579b';")
              .AppendLine("                            } else if (evt.Name === 'PhaseCompleted') {")
              .AppendLine("                                label = `${pipelineInfo}${evt.PhaseId} Completed<br/>${moduleInfo}${evt.Duration.toFixed(0)}ms`;")
              .AppendLine("                                style = 'fill:#c8e6c9,stroke:#2e7d32';")
              .AppendLine("                            } else if (evt.Name === 'PhaseFailed') {")
              .AppendLine("                                const error = evt.Error.length > 30 ? evt.Error.substring(0, 30) + '...' : evt.Error;")
              .AppendLine("                                label = `${pipelineInfo}${evt.PhaseId} Failed<br/>${moduleInfo}${error}`;")
              .AppendLine("                                style = 'fill:#ffcdd2,stroke:#c62828';")
              .AppendLine("                            }")
              .AppendLine("")
              .AppendLine("                            mermaidCode += `            ${eventId}[\\\"${label}\\\"]\\n`;")
              .AppendLine("                            mermaidCode += `            style ${eventId} ${style}\\n`;")
              .AppendLine("")
              .AppendLine("                            if (previousEventId) {")
              .AppendLine("                                mermaidCode += `            ${previousEventId} --> ${eventId}\\n`;")
              .AppendLine("                            }")
              .AppendLine("")
              .AppendLine("                            previousEventId = eventId;")
              .AppendLine("                        });")
              .AppendLine("                    }")
              .AppendLine("")
              .AppendLine("                    mermaidCode += '        end\\n';")
              .AppendLine("                }")
              .AppendLine("")
              .AppendLine("                mermaidCode += '    end\\n';")
              .AppendLine("            }")
              .AppendLine("")
              .AppendLine("            addPipelineLinksAndRender(mermaidCode);")
              .AppendLine("        }")
              .AppendLine("")
              .AppendLine("        function generateDiagramGroupedByPhase() {")
              .AppendLine("            let mermaidCode = 'graph TD\\n';")
              .AppendLine("")
              .AppendLine("            const eventsByPipeline = {};")
              .AppendLine("            filteredEvents.forEach(e => {")
              .AppendLine("                if (!eventsByPipeline[e.PipelineId]) eventsByPipeline[e.PipelineId] = [];")
              .AppendLine("                eventsByPipeline[e.PipelineId].push(e);")
              .AppendLine("            });")
              .AppendLine("")
              .AppendLine("            for (const [pipelineId, events] of Object.entries(eventsByPipeline)) {")
              .AppendLine("                const safePipelineId = sanitizeId(pipelineId);")
              .AppendLine("                mermaidCode += `    subgraph ${safePipelineId}[\\\"${pipelineId}\\\"]\\n`;")
              .AppendLine("")
              .AppendLine("                const eventsByPhase = {};")
              .AppendLine("                events.forEach(e => {")
              .AppendLine("                    if (!eventsByPhase[e.PhaseId]) eventsByPhase[e.PhaseId] = [];")
              .AppendLine("                    eventsByPhase[e.PhaseId].push(e);")
              .AppendLine("                });")
              .AppendLine("")
              .AppendLine("                let previousEventId = null;")
              .AppendLine("")
              .AppendLine("                for (const [phaseId, phaseEvents] of Object.entries(eventsByPhase)) {")
              .AppendLine("                    const safePhaseId = sanitizeId(phaseId);")
              .AppendLine("                    mermaidCode += `        subgraph ${safePipelineId}_${safePhaseId}[\\\"${phaseId}\\\"]\\n`;")
              .AppendLine("")
              .AppendLine("                    let previousPhaseEventId = null;")
              .AppendLine("")
              .AppendLine("                    phaseEvents.forEach((evt, idx) => {")
              .AppendLine("                        const eventId = `${safePipelineId}_${safePhaseId}_evt${idx}`;")
              .AppendLine("                        const itemInfo = evt.ItemId ? `<br/>Item: ${evt.ItemId}` : '';")
              .AppendLine("                        const moduleInfo = evt.ModuleId ? `<br/>Module: ${evt.ModuleId}` : '';")
              .AppendLine("")
              .AppendLine("                        let label = '';")
              .AppendLine("                        let style = '';")
              .AppendLine("")
              .AppendLine("                        if (evt.Name === 'PhaseStarted') {")
              .AppendLine("                            const time = new Date(evt.Timestamp).toLocaleTimeString();")
              .AppendLine("                            label = `Started${moduleInfo}${itemInfo}<br/>${time}`;")
              .AppendLine("                            style = 'fill:#e1f5fe,stroke:#01579b';")
              .AppendLine("                        } else if (evt.Name === 'PhaseCompleted') {")
              .AppendLine("                            label = `Completed${moduleInfo}${itemInfo}<br/>${evt.Duration.toFixed(0)}ms`;")
              .AppendLine("                            style = 'fill:#c8e6c9,stroke:#2e7d32';")
              .AppendLine("                        } else if (evt.Name === 'PhaseFailed') {")
              .AppendLine("                            const error = evt.Error.length > 50 ? evt.Error.substring(0, 50) + '...' : evt.Error;")
              .AppendLine("                            label = `Failed${moduleInfo}${itemInfo}<br/>${error}`;")
              .AppendLine("                            style = 'fill:#ffcdd2,stroke:#c62828';")
              .AppendLine("                        }")
              .AppendLine("")
              .AppendLine("                        mermaidCode += `            ${eventId}[\\\"${label}\\\"]\\n`;")
              .AppendLine("                        mermaidCode += `            style ${eventId} ${style}\\n`;")
              .AppendLine("")
              .AppendLine("                        if (previousPhaseEventId) {")
              .AppendLine("                            mermaidCode += `            ${previousPhaseEventId} --> ${eventId}\\n`;")
              .AppendLine("                        }")
              .AppendLine("")
              .AppendLine("                        previousPhaseEventId = eventId;")
              .AppendLine("                    });")
              .AppendLine("")
              .AppendLine("                    mermaidCode += '        end\\n';")
              .AppendLine("")
              .AppendLine("                    if (previousEventId) {")
              .AppendLine("                        mermaidCode += `        ${previousEventId} -.-> ${previousPhaseEventId}\\n`;")
              .AppendLine("                    }")
              .AppendLine("                    previousEventId = previousPhaseEventId;")
              .AppendLine("                }")
              .AppendLine("")
              .AppendLine("                mermaidCode += '    end\\n';")
              .AppendLine("            }")
              .AppendLine("")
              .AppendLine("            addPipelineLinksAndRender(mermaidCode);")
              .AppendLine("        }")
              .AppendLine("")
              .AppendLine("        function addPipelineLinksAndRender(mermaidCode) {")
              .AppendLine("            // Add pipeline hierarchy links if enabled")
              .AppendLine("            const showPipelineLinks = document.getElementById('showPipelineLinks').checked;")
              .AppendLine("            if (showPipelineLinks) {")
              .AppendLine("                const pipelineLinks = {};")
              .AppendLine("                filteredEvents.forEach(e => {")
              .AppendLine("                    if (e.ParentPipelineId && !pipelineLinks[e.PipelineId]) {")
              .AppendLine("                        pipelineLinks[e.PipelineId] = e.ParentPipelineId;")
              .AppendLine("                    }")
              .AppendLine("                });")
              .AppendLine("")
              .AppendLine("                for (const [childPipelineId, parentPipelineId] of Object.entries(pipelineLinks)) {")
              .AppendLine("                    const safeChildId = sanitizeId(childPipelineId);")
              .AppendLine("                    const safeParentId = sanitizeId(parentPipelineId);")
              .AppendLine("                    mermaidCode += `    ${safeParentId} ==>|sub-pipeline| ${safeChildId}\\n`;")
              .AppendLine("                }")
              .AppendLine("            }")
              .AppendLine("")
              .AppendLine("            const container = document.getElementById('mermaidDiagram');")
              .AppendLine("            container.innerHTML = mermaidCode;")
              .AppendLine("            container.removeAttribute('data-processed');")
              .AppendLine("            window.mermaid.run({ nodes: [container] });")
              .AppendLine("        }")
              .AppendLine("")
              .AppendLine("        // Re-generate diagram when checkboxes change")
              .AppendLine("        document.getElementById('showPipelineLinks')?.addEventListener('change', () => {")
              .AppendLine("            generateDiagram();")
              .AppendLine("        });")
              .AppendLine("")
              .AppendLine("        document.getElementById('groupByItem')?.addEventListener('change', () => {")
              .AppendLine("            generateDiagram();")
              .AppendLine("        });")
              .AppendLine("")
              .AppendLine("        document.getElementById('showPipelineId')?.addEventListener('change', () => {")
              .AppendLine("            generateDiagram();")
              .AppendLine("        });")
              .AppendLine("")
              .AppendLine("        // Initialize on page load")
              .AppendLine("        document.addEventListener('DOMContentLoaded', () => {")
              .AppendLine("            populateFilters();")
              .AppendLine("            applyFilters();")
              .AppendLine("        });")
              .AppendLine("    </script>")
              .AppendLine("</body>")
              .AppendLine("</html>");

        return sb.ToString();
    }
}
