using System.Text.Json;
using System.Text.Json.Nodes;

using ContextCompiler.Abstractions.Configuration;

namespace ContextCompiler.Configuration.Json;

internal sealed class SchemaAggregator : IConfigurationSchemaAggregator
{

    public bool CanAggregate(ISchema schema)
    {
        return Path.GetExtension(schema.Path) == ".json";
    }

    public static JsonObject LoadJsonObject(ISchema schema)
    {
        JsonNode? node = JsonNode.Parse(schema.Content);
        return node as JsonObject ?? [];
    }

    public Task<IAggregatedSchema> Aggregate(ISchema schema1, ISchema schema2)
    {
        JsonObject root = LoadJsonObject(schema1);

        JsonObject defs = root["$defs"] as JsonObject ?? [];
        root["$defs"] = defs;

        List<string> defNames = [];
        JsonObject plugin = LoadJsonObject(schema2);
        string defName = MakeSafeDefName(schema2, plugin);

        JsonObject rewritten = RewritePluginSchemaForEmbedding(plugin, defName);
        defs[defName] = rewritten;
        defNames.Add(defName);

        MergePluginOptionsDefIfPresent(root, rewritten, defName);

        if (defNames.Count > 0)
        {
            ApplyFilesOptionsOneOf(root, defNames);
        }

        root["$comment"] = "Generated by ctxc plugins restore. Aggregates core schema + plugin schemas.";

        return Task.FromResult<IAggregatedSchema>(new JsonAggregatedSchema()
        {
            Content = root.ToJsonString(new JsonSerializerOptions { WriteIndented = true }),
            Name = $"{Path.GetFileNameWithoutExtension(schema1.Name)}_Aggregated",
            Path = schema1.Path
        });
    }

    private static void MergePluginOptionsDefIfPresent(JsonObject root, JsonObject pluginSchema, string pluginDefName)
    {
        JsonObject? rootDefs = root["$defs"] as JsonObject;
        if (rootDefs?["pluginOptions"] is not JsonObject pluginOptionsDef)
        {
            return;
        }

        if (pluginSchema["$defs"] is not JsonObject pluginDefs)
        {
            return;
        }

        if (pluginDefs["pluginOptions"] is not JsonObject pluginProvidedOptions)
        {
            return;
        }

        if (pluginOptionsDef["properties"] is not JsonObject)
        {
            pluginOptionsDef["properties"] = new JsonObject();
        }

        if (pluginOptionsDef["oneOf"] is not JsonArray pluginOptionsOneOf)
        {
            pluginOptionsOneOf = [];
            pluginOptionsDef["oneOf"] = pluginOptionsOneOf;
        }

        //string pluginKey = DerivePluginKey(pluginSchema);

        JsonNode pluginExtractItemSchema = ExtractPluginExtractItemSchema(pluginProvidedOptions).DeepClone();
        RewriteRefsRecursive(pluginExtractItemSchema, pluginDefName);

        if (pluginOptionsDef["properties"] is JsonObject pluginOptionsDefProperties)
        {
            foreach (KeyValuePair<string, JsonNode?> pluginOption in pluginProvidedOptions["properties"]?.AsObject() ?? Enumerable.Empty<KeyValuePair<string, JsonNode?>>())
            {
                pluginOptionsDefProperties.Add(pluginOption.Key, pluginOption.Value?.DeepClone());
                pluginOptionsOneOf.Add(new JsonObject
                {
                    ["required"] = new JsonArray(pluginOption.Key)
                });
            }
        }

        //JsonObject variant = new()
        //{
        //    ["type"] = "object",
        //    ["additionalProperties"] = false,
        //    ["required"] = new JsonArray(pluginKey),
        //    ["properties"] = new JsonObject
        //    {
        //        [pluginKey] = new JsonObject
        //        {
        //            ["type"] = "object",
        //            ["additionalProperties"] = false,
        //            ["properties"] = new JsonObject
        //            {
        //                ["extracts"] = new JsonObject
        //                {
        //                    ["type"] = "array",
        //                    ["items"] = new JsonObject
        //                    {
        //                        ["oneOf"] = new JsonArray(pluginExtractItemSchema)
        //                    }
        //                }
        //            }
        //        }
        //    }
        //};

        //pluginOptionsOneOf.Add(variant);
    }

    private static string DerivePluginKey(JsonObject pluginSchema)
    {
        if (pluginSchema["$defs"] is JsonObject defs
            && defs["pluginMeta"] is JsonObject meta
            && meta["properties"] is JsonObject props
            && props["pluginKey"] is JsonObject pluginKeySchema)
        {
            string? key = pluginKeySchema["const"]?.GetValue<string?>();
            if (!string.IsNullOrWhiteSpace(key))
            {
                return key;
            }

            if (pluginKeySchema["enum"] is JsonArray arr && arr.Count > 0)
            {
                string? enumKey = arr[0]?.GetValue<string?>();
                if (!string.IsNullOrWhiteSpace(enumKey))
                {
                    return enumKey;
                }
            }
        }

        throw new InvalidOperationException("Plugin schema missing $defs.pluginMeta.pluginKey");
    }

    private static JsonObject ExtractPluginExtractItemSchema(JsonObject pluginProvidedOptions)
    {
        if (pluginProvidedOptions["properties"] is not JsonObject props)
        {
            return pluginProvidedOptions;
        }

        if (props["extracts"] is not JsonObject extracts)
        {
            return pluginProvidedOptions;
        }

        if (extracts["items"] is not JsonObject items)
        {
            return pluginProvidedOptions;
        }

        // If items is already a schema object, return it. (If plugin uses array schema with oneOf inside, it can still work.)
        return items;
    }

    private static JsonObject RewritePluginSchemaForEmbedding(JsonObject pluginSchema, string pluginDefName)
    {
        JsonNode clone = pluginSchema.DeepClone();
        RewriteRefsRecursive(clone, pluginDefName);
        return clone as JsonObject ?? [];
    }

    private static void RewriteRefsRecursive(JsonNode node, string pluginDefName)
    {
        if (node is JsonObject obj)
        {
            foreach ((string key, JsonNode? value) in obj.ToList())
            {
                if (key == "$ref" && value is JsonValue v)
                {
                    string? s = v.GetValue<string?>();
                    if (TryRewritePluginLocalRef(s, pluginDefName, out string? rewritten))
                    {
                        obj[key] = rewritten;
                    }
                    continue;
                }

                if (value is not null)
                {
                    RewriteRefsRecursive(value, pluginDefName);
                }
            }
        }
        else if (node is JsonArray arr)
        {
            foreach (JsonNode? item in arr)
            {
                if (item is not null)
                {
                    RewriteRefsRecursive(item, pluginDefName);
                }
            }
        }
    }

    private static bool TryRewritePluginLocalRef(string? refValue, string pluginDefName, out string? rewritten)
    {
        rewritten = null;
        if (string.IsNullOrWhiteSpace(refValue))
        {
            return false;
        }

        const string prefix = "#/$defs/";
        if (!refValue.StartsWith(prefix, StringComparison.Ordinal))
        {
            return false;
        }

        string alreadyPrefixed = $"#/$defs/{pluginDefName}/";
        if (refValue.StartsWith(alreadyPrefixed, StringComparison.Ordinal))
        {
            return false;
        }

        // The plugin schema is embedded under `#/$defs/<pluginDefName>`.
        // Rewrite `#/$defs/x` -> `#/$defs/<pluginDefName>/$defs/x`.
        rewritten = $"#/$defs/{pluginDefName}/$defs/{refValue[prefix.Length..]}";
        return true;
    }

    private static void ApplyFilesOptionsOneOf(JsonObject root, List<string> defNames)
    {
        JsonObject? properties = root["properties"] as JsonObject;
        JsonObject? files = properties?["files"] as JsonObject;
        JsonObject? items = files?["items"] as JsonObject;
        JsonObject? fileProps = items?["properties"] as JsonObject;
        if (fileProps?["options"] is not JsonObject options)
        {
            return;
        }

        JsonArray oneOf = [];

        // allow empty/unspecified options
        oneOf.Add(new JsonObject
        {
            ["type"] = "object",
            ["additionalProperties"] = true
        });

        foreach (string defName in defNames.OrderBy(n => n, StringComparer.OrdinalIgnoreCase))
        {
            oneOf.Add(new JsonObject { ["$ref"] = $"#/$defs/{defName}" });
        }

        options["oneOf"] = oneOf;
        _ = options.Remove("additionalProperties");
    }

    public static string MakeSafeDefName(ISchema schema, JsonObject pluginSchema)
    {
        string? id = pluginSchema["$id"]?.GetValue<string?>();
        return !string.IsNullOrWhiteSpace(id)
            ? Sanitize(id)
            : Sanitize(Path.GetFileNameWithoutExtension(schema.Path));
    }

    private static string Sanitize(string s)
    {
        Span<char> buf = stackalloc char[s.Length];
        int j = 0;
        foreach (char c in s)
        {
            buf[j++] = char.IsLetterOrDigit(c) ? c : '_';
        }
        return new string(buf[..j]);
    }

    public static void Write(JsonObject schema, string path)
    {
        _ = Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, schema.ToJsonString(new JsonSerializerOptions { WriteIndented = true }));
    }
}
