<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;DebugLocal</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="default.md" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Templates\prompt.context.md" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Scriban" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ContextCompiler.Abstractions\ContextCompiler.Abstractions.csproj" />
    <ProjectReference Include="..\ContextCompiler.Modules.Abstractions\ContextCompiler.Modules.Abstractions.csproj" />
  </ItemGroup>

</Project>
