<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>ContextCompiler.DevTools.Modules.SourcesConsole</PackageId>
    <Description>ContextCompiler module that displays sources to the console for debugging and development purposes.</Description>
    <IsPackable>true</IsPackable>
    <Configurations>Debug;Release;DebugLocal</Configurations>
    <Title>Sources Console DevTools module</Title>
    <PackageTags>context;compiler;module;devtools;sources;console;debug</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'DebugLocal'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Core\ContextCompiler.Modules.Abstractions\ContextCompiler.Modules.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
