using System.Globalization;
using System.Text;

namespace ContextCompiler.Modules.Reports.Pipelines.Mermaid;

internal static class MermaidHtmlGenerator
{
    public static string GenerateHtml(string mermaidDiagram, string title = "Pipeline Execution Report")
    {
        StringBuilder sb = new();

        _ = sb.AppendLine("<!DOCTYPE html>")
              .AppendLine("<html lang=\"en\">")
              .AppendLine("<head>")
              .AppendLine("    <meta charset=\"UTF-8\">")
              .AppendLine("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">")
              .AppendLine(CultureInfo.InvariantCulture, $"    <title>{title}</title>")
              .AppendLine("    <script type=\"module\">")
              .AppendLine("        import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';")
              .AppendLine("        mermaid.initialize({ ")
              .AppendLine("            startOnLoad: true,")
              .AppendLine("            theme: 'default',")
              .AppendLine("            flowchart: {")
              .AppendLine("                useMaxWidth: true,")
              .AppendLine("                htmlLabels: true,")
              .AppendLine("                curve: 'basis'")
              .AppendLine("            }")
              .AppendLine("        });")
              .AppendLine("    </script>")
              .AppendLine("    <style>")
              .AppendLine("        body {")
              .AppendLine("            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;")
              .AppendLine("            margin: 0;")
              .AppendLine("            padding: 20px;")
              .AppendLine("            background: #f5f5f5;")
              .AppendLine("        }")
              .AppendLine("        .container {")
              .AppendLine("            max-width: 1400px;")
              .AppendLine("            margin: 0 auto;")
              .AppendLine("            background: white;")
              .AppendLine("            padding: 30px;")
              .AppendLine("            border-radius: 8px;")
              .AppendLine("            box-shadow: 0 2px 4px rgba(0,0,0,0.1);")
              .AppendLine("        }")
              .AppendLine("        h1 {")
              .AppendLine("            color: #333;")
              .AppendLine("            margin-top: 0;")
              .AppendLine("            border-bottom: 3px solid #01579b;")
              .AppendLine("            padding-bottom: 10px;")
              .AppendLine("        }")
              .AppendLine("        .mermaid {")
              .AppendLine("            margin: 20px 0;")
              .AppendLine("            text-align: center;")
              .AppendLine("        }")
              .AppendLine("        .legend {")
              .AppendLine("            margin-top: 30px;")
              .AppendLine("            padding: 15px;")
              .AppendLine("            background: #f9f9f9;")
              .AppendLine("            border-radius: 4px;")
              .AppendLine("        }")
              .AppendLine("        .legend h3 {")
              .AppendLine("            margin-top: 0;")
              .AppendLine("            color: #555;")
              .AppendLine("        }")
              .AppendLine("        .legend-item {")
              .AppendLine("            display: inline-block;")
              .AppendLine("            margin-right: 20px;")
              .AppendLine("            margin-bottom: 10px;")
              .AppendLine("        }")
              .AppendLine("        .legend-box {")
              .AppendLine("            display: inline-block;")
              .AppendLine("            width: 20px;")
              .AppendLine("            height: 20px;")
              .AppendLine("            margin-right: 8px;")
              .AppendLine("            vertical-align: middle;")
              .AppendLine("            border-radius: 3px;")
              .AppendLine("        }")
              .AppendLine("        .started { background: #e1f5fe; border: 2px solid #01579b; }")
              .AppendLine("        .completed { background: #c8e6c9; border: 2px solid #2e7d32; }")
              .AppendLine("        .failed { background: #ffcdd2; border: 2px solid #c62828; }")
              .AppendLine("        .timestamp {")
              .AppendLine("            color: #666;")
              .AppendLine("            font-size: 0.9em;")
              .AppendLine("            margin-top: 20px;")
              .AppendLine("        }")
              .AppendLine("    </style>")
              .AppendLine("</head>")
              .AppendLine("<body>")
              .AppendLine("    <div class=\"container\">")
              .AppendLine(CultureInfo.InvariantCulture, $"        <h1>{title}</h1>")
              .AppendLine("        <div class=\"mermaid\">")
              .AppendLine(mermaidDiagram)
              .AppendLine("        </div>")
              .AppendLine("        <div class=\"legend\">")
              .AppendLine("            <h3>Legend</h3>")
              .AppendLine("            <div class=\"legend-item\">")
              .AppendLine("                <span class=\"legend-box started\"></span>")
              .AppendLine("                <span>Phase Started</span>")
              .AppendLine("            </div>")
              .AppendLine("            <div class=\"legend-item\">")
              .AppendLine("                <span class=\"legend-box completed\"></span>")
              .AppendLine("                <span>Phase Completed</span>")
              .AppendLine("            </div>")
              .AppendLine("            <div class=\"legend-item\">")
              .AppendLine("                <span class=\"legend-box failed\"></span>")
              .AppendLine("                <span>Phase Failed</span>")
              .AppendLine("            </div>")
              .AppendLine("        </div>")
              .AppendLine(CultureInfo.InvariantCulture, $"        <div class=\"timestamp\">Generated: {DateTimeOffset.UtcNow:yyyy-MM-dd HH:mm:ss} UTC</div>")
              .AppendLine("    </div>")
              .AppendLine("</body>")
              .AppendLine("</html>");

        return sb.ToString();
    }
}
